
package co.gov.supernotariado.bachue.clientebus.bancarizacion.operacion;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import co.gov.supernotariado.bachue.clientebus.bancarizacion.type.consultarInformacionmatricula.RespuestaConsultarInformacionMatricula;
import co.gov.supernotariado.bachue.clientebus.bancarizacion.type.consultarcertificadostransaccion.EntidadConsultarCertificadosTransaccion;
import co.gov.supernotariado.bachue.clientebus.bancarizacion.type.consultarestadooficinasregistro.RespuestaConsultarEstadoOficinas;
import co.gov.supernotariado.bachue.clientebus.bancarizacion.type.consultarestadotransaccionconvenio.RespuestaConsultarEstadoTransaccionConvenio;
import co.gov.supernotariado.bachue.clientebus.bancarizacion.type.consultarinformacionmatriculamasivas.EntidadMatriculaSalida;
import co.gov.supernotariado.bachue.clientebus.bancarizacion.type.consultarsaldocuentaprepago.RespuestaConsultarSaldoCuentaPrepago;
import co.gov.supernotariado.bachue.clientebus.bancarizacion.type.consultartarifaconvenio.RespuestaConsultarTarifaConvenio;
import co.gov.supernotariado.bachue.clientebus.bancarizacion.type.consultarurlcertificadostransaccion.EntidadConsultarCertificadosTransaccionURL;
import co.gov.supernotariado.bachue.clientebus.bancarizacion.type.descargarresultadoconsulta.RespuestaDescargarResultadoConsulta;
import co.gov.supernotariado.bachue.clientebus.bancarizacion.type.generarpinprepago.RespuestaGenerarPINPrepago;
import co.gov.supernotariado.bachue.clientebus.bancarizacion.type.generartransaccion.EntidadMatricula;
import co.gov.supernotariado.bachue.clientebus.bancarizacion.type.generartransaccionconsulta.RespuestaGenerarTransaccionConsulta;
import co.gov.supernotariado.bachue.clientebus.bancarizacion.type.generartransaccionextendida.RespuestaGenerarTransaccion;
import co.gov.supernotariado.bachue.clientebus.bancarizacion.type.generico.RespuestaGeneralTransaccion;
import co.gov.supernotariado.bachue.clientebus.bancarizacion.type.solicitarturnorel.RespuestaSolicitarTurnoREL;



/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiciosCertificados", targetNamespace = "http://services.ctls.supernotariado.gov.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiciosCertificados {


    /**
     * 
     * @param claveWS
     * @param codigoServicio
     * @param codigoConvenio
     * @param usuarioWS
     * @return
     *     returns co.gov.supernotariado.ctls.services.RespuestaConsultarSaldoCuentaPrepago
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarSaldoCuentaPrepago", targetNamespace = "http://services.ctls.supernotariado.gov.co/")//, className = "co.gov.supernotariado.ctls.services.ConsultarSaldoCuentaPrepago")
    @ResponseWrapper(localName = "consultarSaldoCuentaPrepagoResponse", targetNamespace = "http://services.ctls.supernotariado.gov.co/")//, className = "co.gov.supernotariado.ctls.services.ConsultarSaldoCuentaPrepagoResponse")
    @Action(input = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/consultarSaldoCuentaPrepagoRequest", output = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/consultarSaldoCuentaPrepagoResponse")
    public RespuestaConsultarSaldoCuentaPrepago consultarSaldoCuentaPrepago(
        @WebParam(name = "usuarioWS", targetNamespace = "")
        String usuarioWS,
        @WebParam(name = "claveWS", targetNamespace = "")
        String claveWS,
        @WebParam(name = "codigoConvenio", targetNamespace = "")
        String codigoConvenio,
        @WebParam(name = "codigoServicio", targetNamespace = "")
        String codigoServicio);

    /**
     * 
     * @param claveWS
     * @param codigoServicio
     * @param tipoConsulta
     * @param codigoConvenio
     * @param usuarioWS
     * @return
     *     returns co.gov.supernotariado.ctls.services.RespuestaConsultarEstadoOficinas
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarEstadoOficinasRegistro", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.ConsultarEstadoOficinasRegistro")
    @ResponseWrapper(localName = "consultarEstadoOficinasRegistroResponse", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.ConsultarEstadoOficinasRegistroResponse")
    @Action(input = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/consultarEstadoOficinasRegistroRequest", output = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/consultarEstadoOficinasRegistroResponse")
    public RespuestaConsultarEstadoOficinas consultarEstadoOficinasRegistro(
        @WebParam(name = "usuarioWS", targetNamespace = "")
        String usuarioWS,
        @WebParam(name = "claveWS", targetNamespace = "")
        String claveWS,
        @WebParam(name = "codigoConvenio", targetNamespace = "")
        String codigoConvenio,
        @WebParam(name = "codigoServicio", targetNamespace = "")
        String codigoServicio,
        @WebParam(name = "tipoConsulta", targetNamespace = "")
        String tipoConsulta);

    /**
     * 
     * @param claveWS
     * @param codigoServicio
     * @param identificadorConvenio
     * @param matricula
     * @param codigoConvenio
     * @param usuarioWS
     * @param codigoCirculo
     * @return
     *     returns co.gov.supernotariado.ctls.services.RespuestaGenerarPINPrepago
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generarPINPrepago", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.GenerarPINPrepago")
    @ResponseWrapper(localName = "generarPINPrepagoResponse", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.GenerarPINPrepagoResponse")
    @Action(input = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/generarPINPrepagoRequest", output = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/generarPINPrepagoResponse")
    public RespuestaGenerarPINPrepago generarPINPrepago(
        @WebParam(name = "usuarioWS", targetNamespace = "")
        String usuarioWS,
        @WebParam(name = "claveWS", targetNamespace = "")
        String claveWS,
        @WebParam(name = "codigoConvenio", targetNamespace = "")
        String codigoConvenio,
        @WebParam(name = "codigoServicio", targetNamespace = "")
        String codigoServicio,
        @WebParam(name = "identificadorConvenio", targetNamespace = "")
        String identificadorConvenio,
        @WebParam(name = "codigoCirculo", targetNamespace = "")
        String codigoCirculo,
        @WebParam(name = "matricula", targetNamespace = "")
        String matricula);

    /**
     * 
     * @param claveWS
     * @param codigoServicio
     * @param codigoConvenio
     * @param usuarioWS
     * @return
     *     returns co.gov.supernotariado.ctls.services.RespuestaConsultarTarifaConvenio
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarTarifaConvenio", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.ConsultarTarifaConvenio")
    @ResponseWrapper(localName = "consultarTarifaConvenioResponse", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.ConsultarTarifaConvenioResponse")
    @Action(input = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/consultarTarifaConvenioRequest", output = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/consultarTarifaConvenioResponse")
    public RespuestaConsultarTarifaConvenio consultarTarifaConvenio(
        @WebParam(name = "usuarioWS", targetNamespace = "")
        String usuarioWS,
        @WebParam(name = "claveWS", targetNamespace = "")
        String claveWS,
        @WebParam(name = "codigoConvenio", targetNamespace = "")
        String codigoConvenio,
        @WebParam(name = "codigoServicio", targetNamespace = "")
        String codigoServicio);

    /**
     * 
     * @param claveWS
     * @param codigoServicio
     * @param codigoTransaccion
     * @param codigoConvenio
     * @param tipoRespuesta
     * @param usuarioWS
     * @return
     *     returns co.gov.supernotariado.ctls.services.RespuestaDescargarResultadoConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "descargarResultadoConsulta", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.DescargarResultadoConsulta")
    @ResponseWrapper(localName = "descargarResultadoConsultaResponse", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.DescargarResultadoConsultaResponse")
    @Action(input = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/descargarResultadoConsultaRequest", output = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/descargarResultadoConsultaResponse")
    public RespuestaDescargarResultadoConsulta descargarResultadoConsulta(
        @WebParam(name = "usuarioWS", targetNamespace = "")
        String usuarioWS,
        @WebParam(name = "claveWS", targetNamespace = "")
        String claveWS,
        @WebParam(name = "codigoConvenio", targetNamespace = "")
        String codigoConvenio,
        @WebParam(name = "codigoServicio", targetNamespace = "")
        String codigoServicio,
        @WebParam(name = "codigoTransaccion", targetNamespace = "")
        Long codigoTransaccion,
        @WebParam(name = "tipoRespuesta", targetNamespace = "")
        String tipoRespuesta);

    /**
     * 
     * @param claveWS
     * @param codigoServicio
     * @param codigoOficina
     * @param codigoTarifa
     * @param matricula
     * @param codigoConvenio
     * @param valorTarifa
     * @param usuarioWS
     * @return
     *     returns co.gov.supernotariado.ctls.services.RespuestaSolicitarTurnoREL
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "solicitarTurnoREL", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.SolicitarTurnoREL")
    @ResponseWrapper(localName = "solicitarTurnoRELResponse", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.SolicitarTurnoRELResponse")
    @Action(input = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/solicitarTurnoRELRequest", output = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/solicitarTurnoRELResponse")
    public RespuestaSolicitarTurnoREL solicitarTurnoREL(
        @WebParam(name = "usuarioWS", targetNamespace = "")
        String usuarioWS,
        @WebParam(name = "claveWS", targetNamespace = "")
        String claveWS,
        @WebParam(name = "codigoConvenio", targetNamespace = "")
        String codigoConvenio,
        @WebParam(name = "codigoServicio", targetNamespace = "")
        String codigoServicio,
        @WebParam(name = "codigoOficina", targetNamespace = "")
        String codigoOficina,
        @WebParam(name = "matricula", targetNamespace = "")
        String matricula,
        @WebParam(name = "codigoTarifa", targetNamespace = "")
        String codigoTarifa,
        @WebParam(name = "valorTarifa", targetNamespace = "")
        Long valorTarifa);

    /**
     * 
     * @param claveWS
     * @param codigoServicio
     * @param codigoConvenio
     * @param matriculas
     * @param usuarioWS
     * @return
     *     returns co.gov.supernotariado.ctls.services.RespuestaGenerarTransaccion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generarTransaccion", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.GenerarTransaccion")
    @ResponseWrapper(localName = "generarTransaccionResponse", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.GenerarTransaccionResponse")
    @Action(input = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/generarTransaccionRequest", output = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/generarTransaccionResponse")
    public RespuestaGenerarTransaccion generarTransaccion(
        @WebParam(name = "usuarioWS", targetNamespace = "")
        String usuarioWS,
        @WebParam(name = "claveWS", targetNamespace = "")
        String claveWS,
        @WebParam(name = "codigoConvenio", targetNamespace = "")
        String codigoConvenio,
        @WebParam(name = "codigoServicio", targetNamespace = "")
        String codigoServicio,
        @WebParam(name = "matriculas", targetNamespace = "")
        List<EntidadMatricula> matriculas);

    /**
     * 
     * @param claveWS
     * @param codigoServicio
     * @param codigoSeguimiento
     * @param codigoConvenio
     * @param matriculas
     * @param usuarioWS
     * @return
     *     returns co.gov.supernotariado.ctls.services.RespuestaGenerarTransaccion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generarTransaccionExtendida", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = " co.gov.supernotariado.bachue.clientebus.bancarizacion.type.GenerarTransaccionExtendida")
    @ResponseWrapper(localName = "generarTransaccionExtendidaResponse", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = " co.gov.supernotariado.bachue.clientebus.bancarizacion.type.GenerarTransaccionExtendidaResponse")
    @Action(input = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/generarTransaccionExtendidaRequest", output = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/generarTransaccionExtendidaResponse")
    public RespuestaGenerarTransaccion generarTransaccionExtendida(
        @WebParam(name = "usuarioWS", targetNamespace = "")
        String usuarioWS,
        @WebParam(name = "claveWS", targetNamespace = "")
        String claveWS,
        @WebParam(name = "codigoConvenio", targetNamespace = "")
        String codigoConvenio,
        @WebParam(name = "codigoServicio", targetNamespace = "")
        String codigoServicio,
        @WebParam(name = "codigoSeguimiento", targetNamespace = "")
        String codigoSeguimiento,
        @WebParam(name = "matriculas", targetNamespace = "")
        List<EntidadMatricula> matriculas);

    /**
     * 
     * @param claveWS
     * @param codigoServicio
     * @param pinPrepago
     * @param codigoConvenio
     * @param matriculas
     * @param usuarioWS
     * @return
     *     returns co.gov.supernotariado.ctls.services.RespuestaGenerarTransaccion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generarTransaccionPINPrepago", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.GenerarTransaccionPINPrepago")
    @ResponseWrapper(localName = "generarTransaccionPINPrepagoResponse", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.GenerarTransaccionPINPrepagoResponse")
    @Action(input = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/generarTransaccionPINPrepagoRequest", output = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/generarTransaccionPINPrepagoResponse")
    public RespuestaGenerarTransaccion generarTransaccionPINPrepago(
        @WebParam(name = "usuarioWS", targetNamespace = "")
        String usuarioWS,
        @WebParam(name = "claveWS", targetNamespace = "")
        String claveWS,
        @WebParam(name = "codigoConvenio", targetNamespace = "")
        String codigoConvenio,
        @WebParam(name = "codigoServicio", targetNamespace = "")
        String codigoServicio,
        @WebParam(name = "pinPrepago", targetNamespace = "")
        Long pinPrepago,
        @WebParam(name = "matriculas", targetNamespace = "")
        List<EntidadMatricula> matriculas);

    /**
     * 
     * @param claveWS
     * @param codigoServicio
     * @param pinPrepago
     * @param codigoConvenio
     * @param usuarioWS
     * @return
     *     returns co.gov.supernotariado.ctls.services.RespuestaGenerarTransaccion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "solicitarTransaccionPINPrepago", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.SolicitarTransaccionPINPrepago")
    @ResponseWrapper(localName = "solicitarTransaccionPINPrepagoResponse", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.SolicitarTransaccionPINPrepagoResponse")
    @Action(input = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/solicitarTransaccionPINPrepagoRequest", output = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/solicitarTransaccionPINPrepagoResponse")
    public RespuestaGenerarTransaccion solicitarTransaccionPINPrepago(
        @WebParam(name = "usuarioWS", targetNamespace = "")
        String usuarioWS,
        @WebParam(name = "claveWS", targetNamespace = "")
        String claveWS,
        @WebParam(name = "codigoConvenio", targetNamespace = "")
        String codigoConvenio,
        @WebParam(name = "codigoServicio", targetNamespace = "")
        String codigoServicio,
        @WebParam(name = "pinPrepago", targetNamespace = "")
        Long pinPrepago);

    /**
     * 
     * @param claveWS
     * @param codigoServicio
     * @param enviarPorCorreo
     * @param correo
     * @param codigoTransaccion
     * @param codigoConvenio
     * @param codigoPuntoRecaudo
     * @param usuarioWS
     * @return
     *     returns co.gov.supernotariado.ctls.services.RespuestaGeneralTransaccion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "confirmarTransaccion", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.ConfirmarTransaccion")
    @ResponseWrapper(localName = "confirmarTransaccionResponse", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.ConfirmarTransaccionResponse")
    @Action(input = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/confirmarTransaccionRequest", output = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/confirmarTransaccionResponse")
    public RespuestaGeneralTransaccion confirmarTransaccion(
        @WebParam(name = "usuarioWS", targetNamespace = "")
        String usuarioWS,
        @WebParam(name = "claveWS", targetNamespace = "")
        String claveWS,
        @WebParam(name = "codigoConvenio", targetNamespace = "")
        String codigoConvenio,
        @WebParam(name = "codigoServicio", targetNamespace = "")
        String codigoServicio,
        @WebParam(name = "codigoPuntoRecaudo", targetNamespace = "")
        String codigoPuntoRecaudo,
        @WebParam(name = "codigoTransaccion", targetNamespace = "")
        Long codigoTransaccion,
        @WebParam(name = "correo", targetNamespace = "")
        String correo,
        @WebParam(name = "enviarPorCorreo", targetNamespace = "")
        String enviarPorCorreo);

    /**
     * 
     * @param claveWS
     * @param codigoServicio
     * @param enviarPorCorreo
     * @param correo
     * @param codigoMedioPago
     * @param codigoTransaccion
     * @param codigoConvenio
     * @param codigoPuntoRecaudo
     * @param valorFinal
     * @param usuarioWS
     * @return
     *     returns co.gov.supernotariado.ctls.services.RespuestaGeneralTransaccion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "confirmarTransaccionExtendida", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.ConfirmarTransaccionExtendida")
    @ResponseWrapper(localName = "confirmarTransaccionExtendidaResponse", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.ConfirmarTransaccionExtendidaResponse")
    @Action(input = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/confirmarTransaccionExtendidaRequest", output = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/confirmarTransaccionExtendidaResponse")
    public RespuestaGeneralTransaccion confirmarTransaccionExtendida(
        @WebParam(name = "usuarioWS", targetNamespace = "")
        String usuarioWS,
        @WebParam(name = "claveWS", targetNamespace = "")
        String claveWS,
        @WebParam(name = "codigoConvenio", targetNamespace = "")
        String codigoConvenio,
        @WebParam(name = "codigoServicio", targetNamespace = "")
        String codigoServicio,
        @WebParam(name = "codigoPuntoRecaudo", targetNamespace = "")
        String codigoPuntoRecaudo,
        @WebParam(name = "codigoTransaccion", targetNamespace = "")
        Long codigoTransaccion,
        @WebParam(name = "correo", targetNamespace = "")
        String correo,
        @WebParam(name = "enviarPorCorreo", targetNamespace = "")
        String enviarPorCorreo,
        @WebParam(name = "codigoMedioPago", targetNamespace = "")
        Long codigoMedioPago,
        @WebParam(name = "valorFinal", targetNamespace = "")
        Long valorFinal);

    /**
     * 
     * @param claveWS
     * @param codigoServicio
     * @param codigoTransaccion
     * @param codigoConvenio
     * @param turno
     * @param valorFinal
     * @param usuarioWS
     * @return
     *     returns co.gov.supernotariado.ctls.services.RespuestaGeneralTransaccion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "confirmarTransaccionExtendidaREL", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.ConfirmarTransaccionExtendidaREL")
    @ResponseWrapper(localName = "confirmarTransaccionExtendidaRELResponse", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.ConfirmarTransaccionExtendidaRELResponse")
    @Action(input = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/confirmarTransaccionExtendidaRELRequest", output = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/confirmarTransaccionExtendidaRELResponse")
    public RespuestaGeneralTransaccion confirmarTransaccionExtendidaREL(
        @WebParam(name = "usuarioWS", targetNamespace = "")
        String usuarioWS,
        @WebParam(name = "claveWS", targetNamespace = "")
        String claveWS,
        @WebParam(name = "codigoConvenio", targetNamespace = "")
        String codigoConvenio,
        @WebParam(name = "codigoServicio", targetNamespace = "")
        String codigoServicio,
        @WebParam(name = "codigoTransaccion", targetNamespace = "")
        Long codigoTransaccion,
        @WebParam(name = "valorFinal", targetNamespace = "")
        Long valorFinal,
        @WebParam(name = "turno", targetNamespace = "")
        String turno);

    /**
     * 
     * @param claveWS
     * @param codigoServicio
     * @param codigoTransaccion
     * @param codigoConvenio
     * @param usuarioWS
     * @return
     *     returns co.gov.supernotariado.ctls.services.RespuestaGeneralTransaccion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelarTransaccion", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.CancelarTransaccion")
    @ResponseWrapper(localName = "cancelarTransaccionResponse", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.CancelarTransaccionResponse")
    @Action(input = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/cancelarTransaccionRequest", output = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/cancelarTransaccionResponse")
    public RespuestaGeneralTransaccion cancelarTransaccion(
        @WebParam(name = "usuarioWS", targetNamespace = "")
        String usuarioWS,
        @WebParam(name = "claveWS", targetNamespace = "")
        String claveWS,
        @WebParam(name = "codigoConvenio", targetNamespace = "")
        String codigoConvenio,
        @WebParam(name = "codigoServicio", targetNamespace = "")
        String codigoServicio,
        @WebParam(name = "codigoTransaccion", targetNamespace = "")
        Long codigoTransaccion);

    /**
     * 
     * @param claveWS
     * @param codigoServicio
     * @param codigoTransaccion
     * @param codigoConvenio
     * @param usuarioWS
     * @return
     *     returns co.gov.supernotariado.ctls.services.EntidadConsultarCertificadosTransaccion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarCertificadosTransaccion", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.ConsultarCertificadosTransaccion")
    @ResponseWrapper(localName = "consultarCertificadosTransaccionResponse", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.ConsultarCertificadosTransaccionResponse")
    @Action(input = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/consultarCertificadosTransaccionRequest", output = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/consultarCertificadosTransaccionResponse")
    public EntidadConsultarCertificadosTransaccion consultarCertificadosTransaccion(
        @WebParam(name = "usuarioWS", targetNamespace = "")
        String usuarioWS,
        @WebParam(name = "claveWS", targetNamespace = "")
        String claveWS,
        @WebParam(name = "codigoConvenio", targetNamespace = "")
        String codigoConvenio,
        @WebParam(name = "codigoServicio", targetNamespace = "")
        String codigoServicio,
        @WebParam(name = "codigoTransaccion", targetNamespace = "")
        Long codigoTransaccion);

    /**
     * 
     * @param claveWS
     * @param codigoServicio
     * @param codigoTransaccion
     * @param codigoConvenio
     * @param usuarioWS
     * @return
     *     returns co.gov.supernotariado.ctls.services.EntidadConsultarCertificadosTransaccionURL
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarURLCertificadosTransaccion", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.ConsultarURLCertificadosTransaccion")
    @ResponseWrapper(localName = "consultarURLCertificadosTransaccionResponse", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.ConsultarURLCertificadosTransaccionResponse")
    @Action(input = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/consultarURLCertificadosTransaccionRequest", output = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/consultarURLCertificadosTransaccionResponse")
    public EntidadConsultarCertificadosTransaccionURL consultarURLCertificadosTransaccion(
        @WebParam(name = "usuarioWS", targetNamespace = "")
        String usuarioWS,
        @WebParam(name = "claveWS", targetNamespace = "")
        String claveWS,
        @WebParam(name = "codigoConvenio", targetNamespace = "")
        String codigoConvenio,
        @WebParam(name = "codigoServicio", targetNamespace = "")
        String codigoServicio,
        @WebParam(name = "codigoTransaccion", targetNamespace = "")
        Long codigoTransaccion);

    /**
     * 
     * @param claveWS
     * @param codigoServicio
     * @param idSeguimientoConvenio
     * @param confirmacionEntrega
     * @param codigoConvenio
     * @param usuarioWS
     * @return
     *     returns co.gov.supernotariado.ctls.services.RespuestaConsultarEstadoTransaccionConvenio
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarEstadoTransaccionConvenio", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.ConsultarEstadoTransaccionConvenio")
    @ResponseWrapper(localName = "consultarEstadoTransaccionConvenioResponse", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.ConsultarEstadoTransaccionConvenioResponse")
    @Action(input = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/consultarEstadoTransaccionConvenioRequest", output = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/consultarEstadoTransaccionConvenioResponse")
    public RespuestaConsultarEstadoTransaccionConvenio consultarEstadoTransaccionConvenio(
        @WebParam(name = "usuarioWS", targetNamespace = "")
        String usuarioWS,
        @WebParam(name = "claveWS", targetNamespace = "")
        String claveWS,
        @WebParam(name = "codigoConvenio", targetNamespace = "")
        String codigoConvenio,
        @WebParam(name = "codigoServicio", targetNamespace = "")
        String codigoServicio,
        @WebParam(name = "idSeguimientoConvenio", targetNamespace = "")
        String idSeguimientoConvenio,
        @WebParam(name = "confirmacionEntrega", targetNamespace = "")
        String confirmacionEntrega);

    /**
     * 
     * @param claveWS
     * @param codigoServicio
     * @param tipoDocumento
     * @param codigoSeguimiento
     * @param codigoConvenio
     * @param numeroDocumento
     * @param usuarioWS
     * @return
     *     returns co.gov.supernotariado.ctls.services.RespuestaGenerarTransaccionConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generarTransaccionConsulta", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.GenerarTransaccionConsulta")
    @ResponseWrapper(localName = "generarTransaccionConsultaResponse", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.GenerarTransaccionConsultaResponse")
    @Action(input = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/generarTransaccionConsultaRequest", output = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/generarTransaccionConsultaResponse")
    public RespuestaGenerarTransaccionConsulta generarTransaccionConsulta(
        @WebParam(name = "usuarioWS", targetNamespace = "")
        String usuarioWS,
        @WebParam(name = "claveWS", targetNamespace = "")
        String claveWS,
        @WebParam(name = "codigoConvenio", targetNamespace = "")
        String codigoConvenio,
        @WebParam(name = "codigoServicio", targetNamespace = "")
        String codigoServicio,
        @WebParam(name = "codigoSeguimiento", targetNamespace = "")
        String codigoSeguimiento,
        @WebParam(name = "tipoDocumento", targetNamespace = "")
        String tipoDocumento,
        @WebParam(name = "numeroDocumento", targetNamespace = "")
        String numeroDocumento);

    /**
     * 
     * @param claveWS
     * @param codigoServicio
     * @param segundoNombre
     * @param usaMatricula
     * @param codigoSeguimiento
     * @param primerNombre
     * @param primerApellido
     * @param segundoApellido
     * @param usuarioWS
     * @param tipoDocumento
     * @param razonSocial
     * @param codigoConvenio
     * @param usaNombres
     * @param matriculaCatastral
     * @param numeroDocumento
     * @return
     *     returns co.gov.supernotariado.ctls.services.RespuestaGenerarTransaccionConsulta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generarTransaccionConsultaExtendida", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.GenerarTransaccionConsultaExtendida")
    @ResponseWrapper(localName = "generarTransaccionConsultaExtendidaResponse", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.GenerarTransaccionConsultaExtendidaResponse")
    @Action(input = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/generarTransaccionConsultaExtendidaRequest", output = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/generarTransaccionConsultaExtendidaResponse")
    public RespuestaGenerarTransaccionConsulta generarTransaccionConsultaExtendida(
        @WebParam(name = "usuarioWS", targetNamespace = "")
        String usuarioWS,
        @WebParam(name = "claveWS", targetNamespace = "")
        String claveWS,
        @WebParam(name = "codigoConvenio", targetNamespace = "")
        String codigoConvenio,
        @WebParam(name = "codigoServicio", targetNamespace = "")
        String codigoServicio,
        @WebParam(name = "codigoSeguimiento", targetNamespace = "")
        String codigoSeguimiento,
        @WebParam(name = "tipoDocumento", targetNamespace = "")
        String tipoDocumento,
        @WebParam(name = "numeroDocumento", targetNamespace = "")
        String numeroDocumento,
        @WebParam(name = "usaNombres", targetNamespace = "")
        boolean usaNombres,
        @WebParam(name = "primerNombre", targetNamespace = "")
        String primerNombre,
        @WebParam(name = "primerApellido", targetNamespace = "")
        String primerApellido,
        @WebParam(name = "segundoNombre", targetNamespace = "")
        String segundoNombre,
        @WebParam(name = "segundoApellido", targetNamespace = "")
        String segundoApellido,
        @WebParam(name = "razonSocial", targetNamespace = "")
        String razonSocial,
        @WebParam(name = "usaMatricula", targetNamespace = "")
        boolean usaMatricula,
        @WebParam(name = "matriculaCatastral", targetNamespace = "")
        String matriculaCatastral);

    /**
     * 
     * @param claveWS
     * @param codigoServicio
     * @param matricula
     * @param codigoConvenio
     * @param usuarioWS
     * @param codigoCirculo
     * @return
     *     returns co.gov.supernotariado.ctls.services.RespuestaConsultarInformacionMatricula
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarInformacionMatricula", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.ConsultarInformacionMatricula")
    @ResponseWrapper(localName = "consultarInformacionMatriculaResponse", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.ConsultarInformacionMatriculaResponse")
    @Action(input = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/consultarInformacionMatriculaRequest", output = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/consultarInformacionMatriculaResponse")
    public RespuestaConsultarInformacionMatricula consultarInformacionMatricula(
        @WebParam(name = "usuarioWS", targetNamespace = "")
        String usuarioWS,
        @WebParam(name = "claveWS", targetNamespace = "")
        String claveWS,
        @WebParam(name = "codigoConvenio", targetNamespace = "")
        String codigoConvenio,
        @WebParam(name = "codigoServicio", targetNamespace = "")
        String codigoServicio,
        @WebParam(name = "codigoCirculo", targetNamespace = "")
        String codigoCirculo,
        @WebParam(name = "matricula", targetNamespace = "")
        String matricula);

    /**
     * 
     * @param claveWS
     * @param codigoServicio
     * @param codigoConvenio
     * @param matriculas
     * @param usuarioWS
     * @return
     *     returns co.gov.supernotariado.ctls.services.EntidadMatriculaSalida
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarInformacionMatriculaMasivas", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.ConsultarInformacionMatriculaMasivas")
    @ResponseWrapper(localName = "consultarInformacionMatriculaMasivasResponse", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.ConsultarInformacionMatriculaMasivasResponse")
    @Action(input = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/consultarInformacionMatriculaMasivasRequest", output = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/consultarInformacionMatriculaMasivasResponse")
    public EntidadMatriculaSalida consultarInformacionMatriculaMasivas(
        @WebParam(name = "usuarioWS", targetNamespace = "")
        String usuarioWS,
        @WebParam(name = "claveWS", targetNamespace = "")
        String claveWS,
        @WebParam(name = "codigoConvenio", targetNamespace = "")
        String codigoConvenio,
        @WebParam(name = "codigoServicio", targetNamespace = "")
        String codigoServicio,
        @WebParam(name = "matriculas", targetNamespace = "")
        List<EntidadMatricula> matriculas);

    /**
     * 
     * @param claveWS
     * @param codigoServicio
     * @param codigoUsuario
     * @param codigoConvenio
     * @param matriculas
     * @param usuarioWS
     * @return
     *     returns co.gov.supernotariado.ctls.services.RespuestaGenerarTransaccion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generarTransaccionInterna", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.GenerarTransaccionInterna")
    @ResponseWrapper(localName = "generarTransaccionInternaResponse", targetNamespace = "http://services.ctls.supernotariado.gov.co/", className = "co.gov.supernotariado.ctls.services.GenerarTransaccionInternaResponse")
    @Action(input = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/generarTransaccionInternaRequest", output = "http://services.ctls.supernotariado.gov.co/ServiciosCertificados/generarTransaccionInternaResponse")
    public RespuestaGenerarTransaccion generarTransaccionInterna(
        @WebParam(name = "usuarioWS", targetNamespace = "")
        String usuarioWS,
        @WebParam(name = "claveWS", targetNamespace = "")
        String claveWS,
        @WebParam(name = "codigoConvenio", targetNamespace = "")
        String codigoConvenio,
        @WebParam(name = "codigoServicio", targetNamespace = "")
        String codigoServicio,
        @WebParam(name = "matriculas", targetNamespace = "")
        List<EntidadMatricula> matriculas,
        @WebParam(name = "codigoUsuario", targetNamespace = "")
        Long codigoUsuario);

}
