
package co.gov.supernotariado.bachue.clientebus.consultardrrmatriculas.operacion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import co.gov.supernotariado.bachue.clientebus.consultardrrmatriculas.type.consultarrrrmatriculas.ObjectFactory;
import co.gov.supernotariado.bachue.clientebus.consultardrrmatriculas.type.consultarrrrmatriculas.TipoEntradaConsultarRRRMatriculas;
import co.gov.supernotariado.bachue.clientebus.consultardrrmatriculas.type.consultarrrrmatriculas.TipoSalidaConsultarRRRMatriculas;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SBB_EE_RRRMatriculas", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/ee/RRRMatriculas/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SBBEERRRMatriculas {


    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.ee.rrrmatriculas.consultarrrrmatriculas.v1.TipoSalidaConsultarRRRMatriculas
     */
    @WebMethod(operationName = "ConsultarRRRMatriculas", action = "https://www.supernotariado.gov.co/services/bachue/ee/RRRMatriculas/v1/ConsultarRRRMatriculas")
    @WebResult(name = "salidaConsultarRRRMatriculas", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ee/RRRMatriculas/consultarRRRMatriculas/v1", partName = "salida")
    public TipoSalidaConsultarRRRMatriculas consultarRRRMatriculas(
        @WebParam(name = "entradaConsultarRRRMatriculas", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ee/RRRMatriculas/consultarRRRMatriculas/v1", partName = "entrada")
        TipoEntradaConsultarRRRMatriculas entrada);

}
