
package co.gov.supernotariado.bachue.clientebus.enviodocumento.operacion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import co.gov.supernotariado.bachue.clientebus.enviodocumento.types.EnviarDocumentoObjectFactory;
import co.gov.supernotariado.bachue.clientebus.enviodocumento.types.TipoEntradaEnviarDocumento;
import co.gov.supernotariado.bachue.clientebus.enviodocumento.types.TipoSalidaEnviarDocumento;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SUT_CO_EnvioDocumentos", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/co/enviodocumentos/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
	EnviarDocumentoObjectFactory.class
})
public interface SUTCOEnvioDocumentos {


    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.co.enviodocumentos.enviardocumento.v1.TipoSalidaEnviarDocumento
     */
    @WebMethod(operationName = "EnviarDocumento", action = "https://www.supernotariado.gov.co/services/bachue/co/enviodocumentos/v1/EnviarDocumento")
    @WebResult(name = "salidaEnviarDocumento", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/co/enviodocumentos/enviardocumento/v1", partName = "salida")
    public TipoSalidaEnviarDocumento enviarDocumento(
        @WebParam(name = "entradaEnviarDocumento", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/co/enviodocumentos/enviardocumento/v1", partName = "entrada")
        TipoEntradaEnviarDocumento entrada);

}
