package co.gov.supernotariado.bachue.clientebus.consultardatosregistrales.operacion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import co.gov.supernotariado.bachue.clientebus.consultardatosregistrales.types.ConsultaDatosRegistralesObjectFactory;
import co.gov.supernotariado.bachue.clientebus.consultardatosregistrales.types.TipoEntradaConsultarDatosRegistrales;
import co.gov.supernotariado.bachue.clientebus.consultardatosregistrales.types.TipoSalidaConsultarDatosRegistrales;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SDI_CI_ConsultaDatosRegistrales", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/ci/consultadatosregistrales/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ConsultaDatosRegistralesObjectFactory.class
})
public interface SDICIConsultaDatosRegistrales {


    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.ci.consultadatosregistrales.consultardatosregistrales.v1.TipoSalidaConsultarDatosRegistrales
     */
    @WebMethod(operationName = "ConsultarDatosRegistrales", action = "https://www.supernotariado.gov.co/services/bachue/ci/consultadatosregistrales/v1/ConsultarDatosRegistrales")
    @WebResult(name = "salidaConsultarDatosRegistrales", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ci/consultadatosregistrales/consultardatosregistrales/v1", partName = "salida")
    public TipoSalidaConsultarDatosRegistrales consultarDatosRegistrales(
        @WebParam(name = "entradaConsultarDatosRegistrales", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ci/consultadatosregistrales/consultardatosregistrales/v1", partName = "entrada")
        TipoEntradaConsultarDatosRegistrales entrada);

}
