package co.gov.supernotariado.bachue.clientebus.poderes.operacion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import co.gov.supernotariado.bachue.clientebus.poderes.types.consultaPoderes.TipoEntradaConsultarPoder;
import co.gov.supernotariado.bachue.clientebus.poderes.types.consultaPoderes.TipoSalidaConsultarPoder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SAN_EE_ConsultaPoderes", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/co/consultapoderes/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
	ObjectFactoryConsultaPoder.class
})
public interface SANEEConsultaPoderes {


    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.co.consultapoderes.consultarpoder.v1.TipoSalidaConsultarPoder
     */
    @WebMethod(operationName = "ConsultarPoder", action = "https://www.supernotariado.gov.co/services/bachue/co/consultapoderes/v1/ConsultarPoder")
    @WebResult(name = "salidaConsultarPoder", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/co/consultapoderes/consultarpoder/v1", partName = "salida")
    public TipoSalidaConsultarPoder consultarPoder(
        @WebParam(name = "entradaConsultarPoder", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/co/consultapoderes/consultarpoder/v1", partName = "entrada")
        TipoEntradaConsultarPoder entrada);

}
