
package co.gov.supernotariado.bachue.clientebus.gestioncuentacupos.operacion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import co.gov.supernotariado.bachue.clientebus.gestioncuentacupos.types.actualizarentidad.ActualizarEntidadObjectFactory;
import co.gov.supernotariado.bachue.clientebus.gestioncuentacupos.types.actualizarentidad.TipoEntradaActualizarEntidad;
import co.gov.supernotariado.bachue.clientebus.gestioncuentacupos.types.actualizarentidad.TipoSalidaActualizarEntidad;
import co.gov.supernotariado.bachue.clientebus.gestioncuentacupos.types.consultarsaldosnotacredito.ConsultarSaldosNotaCreditoObjectFactory;
import co.gov.supernotariado.bachue.clientebus.gestioncuentacupos.types.consultarsaldosnotacredito.TipoEntradaConsultarSaldosNotaCredito;
import co.gov.supernotariado.bachue.clientebus.gestioncuentacupos.types.consultarsaldosnotacredito.TipoSalidaConsultarSaldosNotaCredito;
import co.gov.supernotariado.bachue.clientebus.gestioncuentacupos.types.cancelarusuario.CancelarUsuarioObjectFactory;
import co.gov.supernotariado.bachue.clientebus.gestioncuentacupos.types.cancelarusuario.TipoEntradaCancelarUsuario;
import co.gov.supernotariado.bachue.clientebus.gestioncuentacupos.types.cancelarusuario.TipoSalidaCancelarUsuario;
import co.gov.supernotariado.bachue.clientebus.gestioncuentacupos.types.consultaridcuentacupo.ConsultarIdCuentaCupoObjectFactory;
import co.gov.supernotariado.bachue.clientebus.gestioncuentacupos.types.consultaridcuentacupo.TipoEntradaConsultarIDCuentaCupo;
import co.gov.supernotariado.bachue.clientebus.gestioncuentacupos.types.consultaridcuentacupo.TipoSalidaConsultarIDCuentaCupo;
import co.gov.supernotariado.bachue.clientebus.gestioncuentacupos.types.consultarmovimientos.ConsultarMovimientosObjectFactory;
import co.gov.supernotariado.bachue.clientebus.gestioncuentacupos.types.consultarmovimientos.TipoEntradaConsultarMovimientos;
import co.gov.supernotariado.bachue.clientebus.gestioncuentacupos.types.consultarmovimientos.TipoSalidaConsultarMovimientos;
import co.gov.supernotariado.bachue.clientebus.gestioncuentacupos.types.consultarsaldo.ConsultarSaldoObjectFactory;
import co.gov.supernotariado.bachue.clientebus.gestioncuentacupos.types.consultarsaldo.TipoEntradaConsultarSaldo;
import co.gov.supernotariado.bachue.clientebus.gestioncuentacupos.types.consultarsaldo.TipoSalidaConsultarSaldo;
import co.gov.supernotariado.bachue.clientebus.gestioncuentacupos.types.consultarusuario.ConsultarUsuarioObjectFactory;
import co.gov.supernotariado.bachue.clientebus.gestioncuentacupos.types.consultarusuario.TipoEntradaConsultarUsuario;
import co.gov.supernotariado.bachue.clientebus.gestioncuentacupos.types.consultarusuario.TipoSalidaConsultarUsuario;
import co.gov.supernotariado.bachue.clientebus.gestioncuentacupos.types.consultarusuarios.ConsultarUsuariosObjectFactory;
import co.gov.supernotariado.bachue.clientebus.gestioncuentacupos.types.consultarusuarios.TipoEntradaConsultarUsuarios;
import co.gov.supernotariado.bachue.clientebus.gestioncuentacupos.types.consultarusuarios.TipoSalidaConsultarUsuarios;
import co.gov.supernotariado.bachue.clientebus.gestioncuentacupos.types.inscribirusuario.InscribirUsuarioObjectFactory;
import co.gov.supernotariado.bachue.clientebus.gestioncuentacupos.types.inscribirusuario.TipoEntradaInscribirUsuario;
import co.gov.supernotariado.bachue.clientebus.gestioncuentacupos.types.inscribirusuario.TipoSalidaInscribirUsuario;
import co.gov.supernotariado.bachue.clientebus.gestioncuentacupos.types.pagarcuentacupo.PagarCuentaCupoObjectFactory;
import co.gov.supernotariado.bachue.clientebus.gestioncuentacupos.types.pagarcuentacupo.TipoEntradaPagarCuentaCupo;
import co.gov.supernotariado.bachue.clientebus.gestioncuentacupos.types.pagarcuentacupo.TipoSalidaPagarCuentaCupo;



/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SBB_CB_GestionCuentaCupos", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/cb/gestioncuentacupos/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
	ConsultarSaldosNotaCreditoObjectFactory.class,
	ActualizarEntidadObjectFactory.class,
	CancelarUsuarioObjectFactory.class,
	ConsultarIdCuentaCupoObjectFactory.class,
	ConsultarMovimientosObjectFactory.class,
	ConsultarSaldoObjectFactory.class,
	ConsultarUsuarioObjectFactory.class,
	ConsultarUsuariosObjectFactory.class,
	InscribirUsuarioObjectFactory.class,
	PagarCuentaCupoObjectFactory.class
})
public interface SBBCBGestionCuentaCupos {


    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.cb.gestioncuentacupos.inscribirusuario.v1.TipoSalidaInscribirUsuario
     */
    @WebMethod(operationName = "InscribirUsuario", action = "https://www.supernotariado.gov.co/services/bachue/cb/gestioncuentacupos/v1/InscribirUsuario")
    @WebResult(name = "salidaInscribirUsuario", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/cb/gestioncuentacupos/inscribirusuario/v1", partName = "salida")
    public TipoSalidaInscribirUsuario inscribirUsuario(
        @WebParam(name = "entradaInscribirUsuario", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/cb/gestioncuentacupos/inscribirusuario/v1", partName = "entrada")
        TipoEntradaInscribirUsuario entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.cb.gestioncuentacupos.cancelarusuario.v1.TipoSalidaCancelarUsuario
     */
    @WebMethod(operationName = "CancelarUsuario", action = "https://www.supernotariado.gov.co/services/bachue/cb/gestioncuentacupos/v1/CancelarUsuario")
    @WebResult(name = "salidaCancelarUsuario", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/cb/gestioncuentacupos/cancelarusuario/v1", partName = "salida")
    public TipoSalidaCancelarUsuario cancelarUsuario(
        @WebParam(name = "entradaCancelarUsuario", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/cb/gestioncuentacupos/cancelarusuario/v1", partName = "entrada")
        TipoEntradaCancelarUsuario entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.cb.gestioncuentacupos.consultarusuario.v1.TipoSalidaConsultarUsuario
     */
    @WebMethod(operationName = "ConsultarUsuario", action = "https://www.supernotariado.gov.co/services/bachue/cb/gestioncuentacupos/v1/ConsultarUsuario")
    @WebResult(name = "salidaConsultarUsuario", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/cb/gestioncuentacupos/consultarusuario/v1", partName = "salida")
    public TipoSalidaConsultarUsuario consultarUsuario(
        @WebParam(name = "entradaConsultarUsuario", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/cb/gestioncuentacupos/consultarusuario/v1", partName = "entrada")
        TipoEntradaConsultarUsuario entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.cb.gestioncuentacupos.consultarusuarios.v1.TipoSalidaConsultarUsuarios
     */
    @WebMethod(operationName = "ConsultarUsuarios", action = "https://www.supernotariado.gov.co/services/bachue/cb/gestioncuentacupos/v1/ConsultarUsuarios")
    @WebResult(name = "salidaConsultarUsuarios", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/cb/gestioncuentacupos/consultarusuarios/v1", partName = "salida")
    public TipoSalidaConsultarUsuarios consultarUsuarios(
        @WebParam(name = "entradaConsultarUsuarios", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/cb/gestioncuentacupos/consultarusuarios/v1", partName = "entrada")
        TipoEntradaConsultarUsuarios entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.cb.gestioncuentacupos.consultarsaldo.v1.TipoSalidaConsultarSaldo
     */
    @WebMethod(operationName = "ConsultarSaldo", action = "https://www.supernotariado.gov.co/services/bachue/cb/gestioncuentacupos/v1/ConsultarSaldo")
    @WebResult(name = "salidaConsultarSaldo", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/cb/gestioncuentacupos/consultarsaldo/v1", partName = "salida")
    public TipoSalidaConsultarSaldo consultarSaldo(
        @WebParam(name = "entradaConsultarSaldo", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/cb/gestioncuentacupos/consultarsaldo/v1", partName = "entrada")
        TipoEntradaConsultarSaldo entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.cb.gestioncuentacupos.consultarmovimientos.v1.TipoSalidaConsultarMovimientos
     */
    @WebMethod(operationName = "ConsultarMovimientos", action = "https://www.supernotariado.gov.co/services/bachue/cb/gestioncuentacupos/v1/ConsultarMovimientos")
    @WebResult(name = "salidaConsultarMovimientos", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/cb/gestioncuentacupos/consultarmovimientos/v1", partName = "salida")
    public TipoSalidaConsultarMovimientos consultarMovimientos(
        @WebParam(name = "entradaConsultarMovimientos", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/cb/gestioncuentacupos/consultarmovimientos/v1", partName = "entrada")
        TipoEntradaConsultarMovimientos entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.cb.gestioncuentacupos.pagarcuentacupo.v1.TipoSalidaPagarCuentaCupo
     */
    @WebMethod(operationName = "PagarCuentaCupo", action = "https://www.supernotariado.gov.co/services/bachue/cb/gestioncuentacupos/v1/PagarCuentaCupo")
    @WebResult(name = "salidaPagarCuentaCupo", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/cb/gestioncuentacupos/pagarcuentacupo/v1", partName = "salida")
    public TipoSalidaPagarCuentaCupo pagarCuentaCupo(
        @WebParam(name = "entradaPagarCuentaCupo", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/cb/gestioncuentacupos/pagarcuentacupo/v1", partName = "entrada")
        TipoEntradaPagarCuentaCupo entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.cb.gestioncuentacupos.consultaridcuentacupo.v1.TipoSalidaConsultarIDCuentaCupo
     */
    @WebMethod(operationName = "ConsultarIDCuentaCupo", action = "https://www.supernotariado.gov.co/services/bachue/cb/gestioncuentacupos/v1/ConsultarIDCuentaCupo")
    @WebResult(name = "salidaConsultarIDCuentaCupo", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/cb/gestioncuentacupos/consultaridcuentacupo/v1", partName = "salida")
    public TipoSalidaConsultarIDCuentaCupo consultarIDCuentaCupo(
        @WebParam(name = "entradaConsultarIDCuentaCupo", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/cb/gestioncuentacupos/consultaridcuentacupo/v1", partName = "entrada")
        TipoEntradaConsultarIDCuentaCupo entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.cb.gestioncuentacupos.actualizarentidad.v1.TipoSalidaActualizarEntidad
     */
    @WebMethod(operationName = "ActualizarEntidad", action = "https://www.supernotariado.gov.co/services/bachue/cb/gestioncuentacupos/v1/ActualizarEntidad")
    @WebResult(name = "salidaActualizarEntidad", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/cb/gestioncuentacupos/actualizarentidad/v1", partName = "salida")
    public TipoSalidaActualizarEntidad actualizarEntidad(
        @WebParam(name = "entradaActualizarEntidad", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/cb/gestioncuentacupos/actualizarentidad/v1", partName = "entrada")
        TipoEntradaActualizarEntidad entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.cb.gestioncuentacupos.consultarsaldosnotacredito.v1.TipoSalidaConsultarSaldosNotaCredito
     */
    @WebMethod(operationName = "consultarSaldosNotaCredito", action = "https://www.supernotariado.gov.co/schemas/bachue/cb/gestioncuentacupos/consultarSaldosNotaCredito/v1")
    @WebResult(name = "salidaConsultarSaldosNotaCredito", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/cb/gestioncuentacupos/consultarSaldosNotaCredito/v1", partName = "salida")
    public TipoSalidaConsultarSaldosNotaCredito consultarSaldosNotaCredito(
        @WebParam(name = "entradaConsultarSaldosNotaCredito", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/cb/gestioncuentacupos/consultarSaldosNotaCredito/v1", partName = "entrada")
        TipoEntradaConsultarSaldosNotaCredito entrada);

}
