
package co.gov.supernotariado.bachue.clientebus.solicituddecorreccion.operacion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import co.gov.supernotariado.bachue.clientebus.solicituddecorreccion.types.ingresosolicitud.IngresoSolicitudObjectFactory;
import co.gov.supernotariado.bachue.clientebus.solicituddecorreccion.types.ingresosolicitud.TipoEntradaIngresoSolicitud;
import co.gov.supernotariado.bachue.clientebus.solicituddecorreccion.types.ingresosolicitud.TipoSalidaIngresoSolicitud;
import co.gov.supernotariado.bachue.clientebus.solicituddecorreccion.types.obtenercausalescorreccion.ObtenerCausalesCorreccionObjectFactory;
import co.gov.supernotariado.bachue.clientebus.solicituddecorreccion.types.obtenercausalescorreccion.TipoObtenerCausalesCorreccion;
import co.gov.supernotariado.bachue.clientebus.solicituddecorreccion.types.obtenercausalescorreccion.TipoSalidaObtenerCausalesCorreccion;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SDI_EE_SolicitudDeCorreccion", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/ee/solicituddecorreccion/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObtenerCausalesCorreccionObjectFactory.class,
    IngresoSolicitudObjectFactory.class
})
public interface SDIEESolicitudDeCorreccion {


    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.ee.solicituddecorreccion.obtenercausalescorreccion.v1.TipoSalidaObtenerCausalesCorreccion
     */
    @WebMethod(operationName = "ObtenerCausalesCorreccion", action = "https://www.supernotariado.gov.co/schemas/bachue/ee/solicituddecorreccion/obtenercausalescorreccion/v1")
    @WebResult(name = "salidaObtenerCausalesCorreccion", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ee/solicituddecorreccion/obtenercausalescorreccion/v1", partName = "salida")
    public TipoSalidaObtenerCausalesCorreccion obtenerCausalesCorreccion(
        @WebParam(name = "entradaObtenerCausalesCorreccion", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ee/solicituddecorreccion/obtenercausalescorreccion/v1", partName = "entrada")
        TipoObtenerCausalesCorreccion entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.ee.solicituddecorreccion.ingresosolicitud.v1.TipoSalidaIngresoSolicitud
     */
    @WebMethod(operationName = "IngresoSolicitud", action = "https://www.supernotariado.gov.co/schemas/bachue/ee/solicituddecorreccion/ingresosolicitud/v1")
    @WebResult(name = "salidaIngresoSolicitud", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ee/solicituddecorreccion/ingresosolicitud/v1", partName = "salida")
    public TipoSalidaIngresoSolicitud ingresoSolicitud(
        @WebParam(name = "entradaIngresoSolicitud", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ee/solicituddecorreccion/ingresosolicitud/v1", partName = "entrada")
        TipoEntradaIngresoSolicitud entrada);

}
