package co.gov.supernotariado.bachue.clientebus.busquedadocumentos.operacion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import co.gov.supernotariado.bachue.clientebus.busquedadocumentos.types.consultar.ConsultarObjectFactory;
import co.gov.supernotariado.bachue.clientebus.busquedadocumentos.types.consultar.TipoEntradaConsultar;
import co.gov.supernotariado.bachue.clientebus.busquedadocumentos.types.consultar.TipoSalidaConsultar;
import co.gov.supernotariado.bachue.clientebus.busquedadocumentos.types.obtenerarchivo.ObtenerArchivoObjectFactory;
import co.gov.supernotariado.bachue.clientebus.busquedadocumentos.types.obtenerarchivo.TipoEntradaObtenerArchivo;
import co.gov.supernotariado.bachue.clientebus.busquedadocumentos.types.obtenerarchivo.TipoSalidaObtenerArchivo;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SUT_CI_BusquedaDocumentos", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/co/busquedadocumentos/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
	ConsultarObjectFactory.class,
	ObtenerArchivoObjectFactory.class
})
public interface SUTCIBusquedaDocumentos {


    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.co.busquedadocumentos.consultar.v1.TipoSalidaConsultar
     */
    @WebMethod(operationName = "Consultar", action = "https://www.supernotariado.gov.co/services/bachue/co/busquedadocumentos/v1/Consultar")
    @WebResult(name = "salidaConsultar", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/co/busquedadocumentos/consultar/v1", partName = "salida")
    public TipoSalidaConsultar consultar(
        @WebParam(name = "entradaConsultar", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/co/busquedadocumentos/consultar/v1", partName = "entrada")
        TipoEntradaConsultar entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.co.busquedadocumentos.obtenerarchivo.v1.TipoSalidaObtenerArchivo
     */
    @WebMethod(operationName = "ObtenerArchivo", action = "https://www.supernotariado.gov.co/services/bachue/co/busquedadocumentos/v1/ObtenerArchivo")
    @WebResult(name = "salidaObtenerArchivo", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/co/busquedadocumentos/obtenerarchivo/v1", partName = "salida")
    public TipoSalidaObtenerArchivo obtenerArchivo(
        @WebParam(name = "entradaObtenerArchivo", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/co/busquedadocumentos/obtenerarchivo/v1", partName = "entrada")
        TipoEntradaObtenerArchivo entrada);

}
