package co.gov.supernotariado.bachue.clientebus.consultacatalogos.operacion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import co.gov.supernotariado.bachue.clientebus.consultacatalogos.types.consultarcatalogos.ConsultarCatalogosObjectFactory;
import co.gov.supernotariado.bachue.clientebus.consultacatalogos.types.consultarcatalogos.TipoEntradaConsultarCatalogos;
import co.gov.supernotariado.bachue.clientebus.consultacatalogos.types.consultarcatalogos.TipoSalidaConsultarCatalogos;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SDI_EE_ConsultaCatalogos", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/ee/consultacatalogos/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ConsultarCatalogosObjectFactory.class
})
public interface SDIEEConsultaCatalogos {


    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.ee.consultacatalogos.consultarcatalogos.v1.TipoSalidaConsultarCatalogos
     */
    @WebMethod(operationName = "ConsultarCatalogos", action = "https://www.supernotariado.gov.co/services/bachue/ee/consultacatalogos/v1/ConsultarCatalogos")
    @WebResult(name = "salidaConsultarCatalogos", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ee/consultacatalogos/consultarcatalogos/v1", partName = "salida")
    public TipoSalidaConsultarCatalogos consultarCatalogos(
        @WebParam(name = "entradaConsultarCatalogos", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ee/consultacatalogos/consultarcatalogos/v1", partName = "entrada")
        TipoEntradaConsultarCatalogos entrada);

}
