package co.gov.supernotariado.bachue.clientebus.gestionalertastitulares.operacion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import co.gov.supernotariado.bachue.clientebus.gestionalertastitulares.types.inactivaralerta.TipoSalidaInactivarAlerta;
import co.gov.supernotariado.bachue.clientebus.gestionalertastitulares.types.actualizarcontactoalerta.ActualizarContactoAlertaObjectFactory;
import co.gov.supernotariado.bachue.clientebus.gestionalertastitulares.types.actualizarcontactoalerta.TipoEntradaActualizarContactoAlerta;
import co.gov.supernotariado.bachue.clientebus.gestionalertastitulares.types.actualizarcontactoalerta.TipoSalidaActualizarContactoAlerta;
import co.gov.supernotariado.bachue.clientebus.gestionalertastitulares.types.consultaralerta.ConsultarAlertaObjectFactory;
import co.gov.supernotariado.bachue.clientebus.gestionalertastitulares.types.consultaralerta.TipoEntradaConsultarAlerta;
import co.gov.supernotariado.bachue.clientebus.gestionalertastitulares.types.consultaralerta.TipoSalidaConsultarAlerta;
import co.gov.supernotariado.bachue.clientebus.gestionalertastitulares.types.consultartarifaalertastitulares.ConsultarTarifaAlertasTitularesObjectFactory;
import co.gov.supernotariado.bachue.clientebus.gestionalertastitulares.types.consultartarifaalertastitulares.TipoEntradaConsultarTarifaAlertasTitulares;
import co.gov.supernotariado.bachue.clientebus.gestionalertastitulares.types.consultartarifaalertastitulares.TipoSalidaConsultarTarifaAlertasTitulares;
import co.gov.supernotariado.bachue.clientebus.gestionalertastitulares.types.inactivaralerta.InactivarAlertaObjectFactory;
import co.gov.supernotariado.bachue.clientebus.gestionalertastitulares.types.inactivaralerta.TipoEntradaInactivarAlerta;
import co.gov.supernotariado.bachue.clientebus.gestionalertastitulares.types.validarsolicitudalertaindividual.TipoEntradaValidarSolicitudAlertaIndividual;
import co.gov.supernotariado.bachue.clientebus.gestionalertastitulares.types.validarsolicitudalertaindividual.TipoSalidaValidarSolicitudAlertaIndividual;
import co.gov.supernotariado.bachue.clientebus.gestionalertastitulares.types.validarsolicitudalertaindividual.ValidarSolicitudAlertaIndividualObjectFactory;
import co.gov.supernotariado.bachue.clientebus.gestionalertastitulares.types.validarsolicitudalertamasiva.TipoEntradaValidarSolicitudAlertaMasiva;
import co.gov.supernotariado.bachue.clientebus.gestionalertastitulares.types.validarsolicitudalertamasiva.TipoSalidaValidarSolicitudAlertaMasiva;
import co.gov.supernotariado.bachue.clientebus.gestionalertastitulares.types.validarsolicitudalertamasiva.ValidarSolicitudAlertaMasivaObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SDI_EE_GestionAlertasTitulares", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/ee/gestionalertastitulares/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
	ActualizarContactoAlertaObjectFactory.class,
	ConsultarAlertaObjectFactory.class,
	ConsultarTarifaAlertasTitularesObjectFactory.class,
	InactivarAlertaObjectFactory.class,
	ValidarSolicitudAlertaIndividualObjectFactory.class,
	ValidarSolicitudAlertaMasivaObjectFactory.class
})
public interface SDIEEGestionAlertasTitulares {


    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.ee.gestionalertastitulares.consultaralerta.v1.TipoSalidaConsultarAlerta
     */
    @WebMethod(operationName = "ConsultarAlerta", action = "https://www.supernotariado.gov.co/services/bachue/ee/gestionalertastitulares/v1/ConsultarAlerta")
    @WebResult(name = "salidaConsultarAlerta", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ee/gestionalertastitulares/consultaralerta/v1", partName = "salida")
    public TipoSalidaConsultarAlerta consultarAlerta(
        @WebParam(name = "entradaConsultarAlerta", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ee/gestionalertastitulares/consultaralerta/v1", partName = "entrada")
        TipoEntradaConsultarAlerta entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.ee.gestionalertastitulares.consultartarifaalertastitulares.v1.TipoSalidaConsultarTarifaAlertasTitulares
     */
    @WebMethod(operationName = "ConsultarTarifaAlertasTitulares", action = "https://www.supernotariado.gov.co/services/bachue/ee/gestionalertastitulares/v1/ConsultarTarifaAlertasTitulares")
    @WebResult(name = "salidaConsultarTarifaAlertasTitulares", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ee/gestionalertastitulares/consultartarifaalertastitulares/v1", partName = "salida")
    public TipoSalidaConsultarTarifaAlertasTitulares consultarTarifaAlertasTitulares(
        @WebParam(name = "entradaConsultarTarifaAlertasTitulares", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ee/gestionalertastitulares/consultartarifaalertastitulares/v1", partName = "entrada")
        TipoEntradaConsultarTarifaAlertasTitulares entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.ee.gestionalertastitulares.inactivaralerta.v1.TipoSalidaInactivarAlerta
     */
    @WebMethod(operationName = "InactivarAlerta", action = "https://www.supernotariado.gov.co/services/bachue/ee/gestionalertastitulares/v1/InactivarAlerta")
    @WebResult(name = "salidaInactivarAlerta", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ee/gestionalertastitulares/inactivaralerta/v1", partName = "salida")
    public TipoSalidaInactivarAlerta inactivarAlerta(
        @WebParam(name = "entradaInactivarAlerta", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ee/gestionalertastitulares/inactivaralerta/v1", partName = "entrada")
        TipoEntradaInactivarAlerta entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.ee.gestionalertastitulares.validarsolicitudalertaindividual.v1.TipoSalidaValidarSolicitudAlertaIndividual
     */
    @WebMethod(operationName = "ValidarSolicitudAlertaIndividual", action = "https://www.supernotariado.gov.co/services/bachue/ee/gestionalertastitulares/v1/ValidarSolicitudAlertaIndividual")
    @WebResult(name = "salidaValidarSolicitudAlertaIndividual", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ee/gestionalertastitulares/validarsolicitudalertaindividual/v1", partName = "salida")
    public TipoSalidaValidarSolicitudAlertaIndividual validarSolicitudAlertaIndividual(
        @WebParam(name = "entradaValidarSolicitudAlertaIndividual", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ee/gestionalertastitulares/validarsolicitudalertaindividual/v1", partName = "entrada")
        TipoEntradaValidarSolicitudAlertaIndividual entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.ee.gestionalertastitulares.validarsolicitudalertamasiva.v1.TipoSalidaValidarSolicitudAlertaMasiva
     */
    @WebMethod(operationName = "ValidarSolicitudAlertaMasiva", action = "https://www.supernotariado.gov.co/services/bachue/ee/gestionalertastitulares/v1/ValidarSolicitudAlertaMasiva")
    @WebResult(name = "salidaValidarSolicitudAlertaMasiva", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ee/gestionalertastitulares/validarsolicitudalertamasiva/v1", partName = "salida")
    public TipoSalidaValidarSolicitudAlertaMasiva validarSolicitudAlertaMasiva(
        @WebParam(name = "entradaValidarSolicitudAlertaMasiva", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ee/gestionalertastitulares/validarsolicitudalertamasiva/v1", partName = "entrada")
        TipoEntradaValidarSolicitudAlertaMasiva entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.ee.gestionalertastitulares.actualizarcontactoalerta.v1.TipoSalidaActualizarContactoAlerta
     */
    @WebMethod(operationName = "ActualizarContactoAlerta", action = "https://www.supernotariado.gov.co/services/bachue/ee/gestionalertastitulares/v1/ActualizarContactoAlerta")
    @WebResult(name = "salidaActualizarContactoAlerta", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ee/gestionalertastitulares/actualizarcontactoalerta/v1", partName = "salida")
    public TipoSalidaActualizarContactoAlerta actualizarContactoAlerta(
        @WebParam(name = "entradaActualizarContactoAlerta", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ee/gestionalertastitulares/actualizarcontactoalerta/v1", partName = "entrada")
        TipoEntradaActualizarContactoAlerta entrada);

}
