package co.gov.supernotariado.bachue.clientebus.estadojuridicofolio.operacion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import co.gov.supernotariado.bachue.clientebus.estadojuridicofolio.types.consultarestadojuridico.ConsultarEstadoJuridicoObjectFactory;
import co.gov.supernotariado.bachue.clientebus.estadojuridicofolio.types.consultarestadojuridico.TipoEntradaConsultaJuridicaFolio;
import co.gov.supernotariado.bachue.clientebus.estadojuridicofolio.types.consultarestadojuridico.TipoSalidaConsultaEstadoJuridicoFolio;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SBB_EE_EstadoJuridicoFolio", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/ee/estadoJuridicoFolio/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
	ConsultarEstadoJuridicoObjectFactory.class
})
public interface SBBEEEstadoJuridicoFolio {


    /**
     * 
     * @param entrada
     * @return
     *     returns co.gov.gobiernoenlinea.gel_xml._1_0.schemas.integracion.supernotariado.bachue.TipoSalidaConsultaEstadoJuridicoFolio
     */
    @WebMethod(operationName = "ConsultarEstadoJuridico", action = "http://www.gobiernoenlinea.gov.co/GEL-XML/1.0/schemas/integracion/supernotariado/bachue")
    @WebResult(name = "consultaEstadoJuridicoRespuesta", targetNamespace = "http://www.gobiernoenlinea.gov.co/GEL-XML/1.0/schemas/integracion/supernotariado/bachue", partName = "salida")
    public TipoSalidaConsultaEstadoJuridicoFolio consultarEstadoJuridico(
        @WebParam(name = "consultaEstadoJuridicaSolicitud", targetNamespace = "http://www.gobiernoenlinea.gov.co/GEL-XML/1.0/schemas/integracion/supernotariado/bachue", partName = "entrada")
        TipoEntradaConsultaJuridicaFolio entrada);

}
