
package co.gov.supernotariado.bachue.clientebus.servicios;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import co.gov.supernotariado.bachue.clientebus.biometriacorebachue.operacion.BiometriaWS;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BiometriaController", targetNamespace = "http://ws.servicios.corebachue.bachue.supernotariado.gov.co/", wsdlLocation = "http://localhost/wsdl/serviciosdispositivos.wsdl")
public class BiometriaController
    extends Service
{

    private final static URL BIOMETRIACONTROLLER_WSDL_LOCATION;
    private final static WebServiceException BIOMETRIACONTROLLER_EXCEPTION;
    private final static QName BIOMETRIACONTROLLER_QNAME = new QName("http://ws.servicios.corebachue.bachue.supernotariado.gov.co/", "BiometriaController");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/wsdl/serviciosdispositivos.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BIOMETRIACONTROLLER_WSDL_LOCATION = url;
        BIOMETRIACONTROLLER_EXCEPTION = e;
    }

    public BiometriaController() {
        super(__getWsdlLocation(), BIOMETRIACONTROLLER_QNAME);
    }

    public BiometriaController(WebServiceFeature... features) {
        super(__getWsdlLocation(), BIOMETRIACONTROLLER_QNAME, features);
    }

    public BiometriaController(URL wsdlLocation) {
        super(wsdlLocation, BIOMETRIACONTROLLER_QNAME);
    }

    public BiometriaController(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BIOMETRIACONTROLLER_QNAME, features);
    }

    public BiometriaController(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BiometriaController(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BiometriaWS
     */
    @WebEndpoint(name = "BiometriaWSPort")
    public BiometriaWS getBiometriaWSPort() {
        return super.getPort(new QName("http://ws.servicios.corebachue.bachue.supernotariado.gov.co/", "BiometriaWSPort"), BiometriaWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BiometriaWS
     */
    @WebEndpoint(name = "BiometriaWSPort")
    public BiometriaWS getBiometriaWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.servicios.corebachue.bachue.supernotariado.gov.co/", "BiometriaWSPort"), BiometriaWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BIOMETRIACONTROLLER_EXCEPTION!= null) {
            throw BIOMETRIACONTROLLER_EXCEPTION;
        }
        return BIOMETRIACONTROLLER_WSDL_LOCATION;
    }

}
