
package co.gov.supernotariado.bachue.clientebus.servicios;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import co.gov.supernotariado.bachue.clientebus.alertatierras.operacion.SBBEEAlertaTierras;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BS_SDI_CB_AlertaTierras", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/ee/alertaTierras/v1", wsdlLocation = "http://localhost/wsdl/BS_SDI_CB_AlertaTierrasPort.wsdl")
public class BSSDICBAlertaTierrasService
    extends Service
{

    private final static URL BSSDICBALERTATIERRAS_WSDL_LOCATION;
    private final static WebServiceException BSSDICBALERTATIERRAS_EXCEPTION;
    private final static QName BSSDICBALERTATIERRAS_QNAME = new QName("https://www.supernotariado.gov.co/services/bachue/ee/alertaTierras/v1", "BS_SDI_CB_AlertaTierras");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/wsdl/BS_SDI_CB_AlertaTierrasPort.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BSSDICBALERTATIERRAS_WSDL_LOCATION = url;
        BSSDICBALERTATIERRAS_EXCEPTION = e;
    }

    public BSSDICBAlertaTierrasService() {
        super(__getWsdlLocation(), BSSDICBALERTATIERRAS_QNAME);
    }

    public BSSDICBAlertaTierrasService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BSSDICBALERTATIERRAS_QNAME, features);
    }

    public BSSDICBAlertaTierrasService(URL wsdlLocation) {
        super(wsdlLocation, BSSDICBALERTATIERRAS_QNAME);
    }

    public BSSDICBAlertaTierrasService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BSSDICBALERTATIERRAS_QNAME, features);
    }

    public BSSDICBAlertaTierrasService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BSSDICBAlertaTierrasService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BSSDICBAlertaTierras
     */
    @WebEndpoint(name = "BS_SDI_CB_AlertaTierrasPort")
    public SBBEEAlertaTierras getBSSDICBAlertaTierrasPort() {
        return super.getPort(new QName("https://www.supernotariado.gov.co/services/bachue/ee/alertaTierras/v1", "BS_SDI_CB_AlertaTierrasPort"), SBBEEAlertaTierras.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BSSDICBAlertaTierras
     */
    @WebEndpoint(name = "BS_SDI_CB_AlertaTierrasPort")
    public SBBEEAlertaTierras getBSSDICBAlertaTierrasPort(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.supernotariado.gov.co/services/bachue/ee/alertaTierras/v1", "BS_SDI_CB_AlertaTierrasPort"), SBBEEAlertaTierras.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BSSDICBALERTATIERRAS_EXCEPTION!= null) {
            throw BSSDICBALERTATIERRAS_EXCEPTION;
        }
        return BSSDICBALERTATIERRAS_WSDL_LOCATION;
    }

}
