package co.gov.supernotariado.bachue.clientebus.servicios;



import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import co.gov.supernotariado.bachue.clientebus.pasarela.operacion.RealPayPort;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RealPayAPI", targetNamespace = "http://soap.dto.services.realpay.nvalue.com.co/", wsdlLocation = "https://developer.realpay.com.co/api/soap/RealPayAPI?wsdl")
public class RealPayAPI
    extends Service
{

    private static final URL CU_REALPAYAPI_WSDL_LOCATION;
    private static final WebServiceException CWSE_REALPAYAPI_EXCEPTION;
    private static final QName CQN_REALPAYAPI_QNAME = new QName("http://soap.dto.services.realpay.nvalue.com.co/", "RealPayAPI");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://developer.realpay.com.co/api/soap/RealPayAPI?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CU_REALPAYAPI_WSDL_LOCATION = url;
        CWSE_REALPAYAPI_EXCEPTION = e;
    }

    public RealPayAPI() {
        super(__getWsdlLocation(), CQN_REALPAYAPI_QNAME);
    }

    public RealPayAPI(WebServiceFeature... features) {
        super(__getWsdlLocation(), CQN_REALPAYAPI_QNAME, features);
    }

    public RealPayAPI(URL wsdlLocation) {
        super(wsdlLocation, CQN_REALPAYAPI_QNAME);
    }

    public RealPayAPI(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CQN_REALPAYAPI_QNAME, features);
    }

    public RealPayAPI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RealPayAPI(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RealPayPort
     */
    @WebEndpoint(name = "RealPayAPIPORTPort")
    public RealPayPort getRealPayAPIPORTPort() {
        return super.getPort(new QName("http://soap.dto.services.realpay.nvalue.com.co/", "RealPayAPIPORTPort"), RealPayPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RealPayPort
     */
    @WebEndpoint(name = "RealPayAPIPORTPort")
    public RealPayPort getRealPayAPIPORTPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.dto.services.realpay.nvalue.com.co/", "RealPayAPIPORTPort"), RealPayPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CWSE_REALPAYAPI_EXCEPTION!= null) {
            throw CWSE_REALPAYAPI_EXCEPTION;
        }
        return CU_REALPAYAPI_WSDL_LOCATION;
    }

}
