package co.gov.supernotariado.bachue.clientebus.servicios;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import co.gov.supernotariado.bachue.clientebus.poderes.operacion.SANEEActualizacionMetadatosPoderes;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SAN_EE_ActualizacionMetadatosPoderes", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/co/actualizacionmetadatospoderes/v1", wsdlLocation = "http://localhost/wsdl/actualizacionMetadatosPoderes.wsdl")
public class SANEEActualizacionMetadatosPoderesService
    extends Service
{

    private final static URL SANEEACTUALIZACIONMETADATOSPODERES_WSDL_LOCATION;
    private final static WebServiceException SANEEACTUALIZACIONMETADATOSPODERES_EXCEPTION;
    private final static QName SANEEACTUALIZACIONMETADATOSPODERES_QNAME = new QName("https://www.supernotariado.gov.co/services/bachue/co/actualizacionmetadatospoderes/v1", "SAN_EE_ActualizacionMetadatosPoderes");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/wsdl/actualizacionMetadatosPoderes.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SANEEACTUALIZACIONMETADATOSPODERES_WSDL_LOCATION = url;
        SANEEACTUALIZACIONMETADATOSPODERES_EXCEPTION = e;
    }

    public SANEEActualizacionMetadatosPoderesService() {
        super(__getWsdlLocation(), SANEEACTUALIZACIONMETADATOSPODERES_QNAME);
    }

    public SANEEActualizacionMetadatosPoderesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SANEEACTUALIZACIONMETADATOSPODERES_QNAME, features);
    }

    public SANEEActualizacionMetadatosPoderesService(URL wsdlLocation) {
        super(wsdlLocation, SANEEACTUALIZACIONMETADATOSPODERES_QNAME);
    }

    public SANEEActualizacionMetadatosPoderesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SANEEACTUALIZACIONMETADATOSPODERES_QNAME, features);
    }

    public SANEEActualizacionMetadatosPoderesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SANEEActualizacionMetadatosPoderesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SANEEActualizacionMetadatosPoderes
     */
    @WebEndpoint(name = "SAN_EE_ActualizacionMetadatosPoderesPort")
    public SANEEActualizacionMetadatosPoderes getSANEEActualizacionMetadatosPoderesPort() {
        return super.getPort(new QName("https://www.supernotariado.gov.co/services/bachue/co/actualizacionmetadatospoderes/v1", "SAN_EE_ActualizacionMetadatosPoderesPort"), SANEEActualizacionMetadatosPoderes.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SANEEActualizacionMetadatosPoderes
     */
    @WebEndpoint(name = "SAN_EE_ActualizacionMetadatosPoderesPort")
    public SANEEActualizacionMetadatosPoderes getSANEEActualizacionMetadatosPoderesPort(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.supernotariado.gov.co/services/bachue/co/actualizacionmetadatospoderes/v1", "SAN_EE_ActualizacionMetadatosPoderesPort"), SANEEActualizacionMetadatosPoderes.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SANEEACTUALIZACIONMETADATOSPODERES_EXCEPTION!= null) {
            throw SANEEACTUALIZACIONMETADATOSPODERES_EXCEPTION;
        }
        return SANEEACTUALIZACIONMETADATOSPODERES_WSDL_LOCATION;
    }

}
