
package co.gov.supernotariado.bachue.clientebus.servicios;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import co.gov.supernotariado.bachue.clientebus.poderes.operacion.SANEEConsultaPoderes;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SAN_EE_ConsultaPoderes", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/co/consultapoderes/v1", wsdlLocation = "http://localhost/wsdl/SAN_EE_ConsultaPoderes.wsdl")
public class SANEEConsultaPoderesService
    extends Service
{

    private final static URL SANEECONSULTAPODERES_WSDL_LOCATION;
    private final static WebServiceException SANEECONSULTAPODERES_EXCEPTION;
    private final static QName SANEECONSULTAPODERES_QNAME = new QName("https://www.supernotariado.gov.co/services/bachue/co/consultapoderes/v1", "SAN_EE_ConsultaPoderes");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/wsdl/SAN_EE_ConsultaPoderes.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SANEECONSULTAPODERES_WSDL_LOCATION = url;
        SANEECONSULTAPODERES_EXCEPTION = e;
    }

    public SANEEConsultaPoderesService() {
        super(__getWsdlLocation(), SANEECONSULTAPODERES_QNAME);
    }

    public SANEEConsultaPoderesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SANEECONSULTAPODERES_QNAME, features);
    }

    public SANEEConsultaPoderesService(URL wsdlLocation) {
        super(wsdlLocation, SANEECONSULTAPODERES_QNAME);
    }

    public SANEEConsultaPoderesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SANEECONSULTAPODERES_QNAME, features);
    }

    public SANEEConsultaPoderesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SANEEConsultaPoderesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SANEEConsultaPoderes
     */
    @WebEndpoint(name = "SAN_EE_ConsultaPoderesPort")
    public SANEEConsultaPoderes getSANEEConsultaPoderesPort() {
        return super.getPort(new QName("https://www.supernotariado.gov.co/services/bachue/co/consultapoderes/v1", "SAN_EE_ConsultaPoderesPort"), SANEEConsultaPoderes.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SANEEConsultaPoderes
     */
    @WebEndpoint(name = "SAN_EE_ConsultaPoderesPort")
    public SANEEConsultaPoderes getSANEEConsultaPoderesPort(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.supernotariado.gov.co/services/bachue/co/consultapoderes/v1", "SAN_EE_ConsultaPoderesPort"), SANEEConsultaPoderes.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SANEECONSULTAPODERES_EXCEPTION!= null) {
            throw SANEECONSULTAPODERES_EXCEPTION;
        }
        return SANEECONSULTAPODERES_WSDL_LOCATION;
    }

}
