
package co.gov.supernotariado.bachue.clientebus.servicios;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import co.gov.supernotariado.bachue.clientebus.gestioncuentacupos.operacion.SBBCBGestionCuentaCupos;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SBB_CB_GestionCuentaCuposSOAP12BindingQSService", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/cb/gestioncuentacupos/v1", wsdlLocation = "http://localhost/wsdl/gestioncuentacupos.wsdl")
public class SBBCBGestionCuentaCuposService
    extends Service
{

    private final static URL SBBCBGESTIONCUENTACUPOSSOAP12BINDINGQSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SBBCBGESTIONCUENTACUPOSSOAP12BINDINGQSSERVICE_EXCEPTION;
    private final static QName SBBCBGESTIONCUENTACUPOSSOAP12BINDINGQSSERVICE_QNAME = new QName("https://www.supernotariado.gov.co/services/bachue/cb/gestioncuentacupos/v1", "SBB_CB_GestionCuentaCuposSOAP12BindingQSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/wsdl/gestioncuentacupos.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SBBCBGESTIONCUENTACUPOSSOAP12BINDINGQSSERVICE_WSDL_LOCATION = url;
        SBBCBGESTIONCUENTACUPOSSOAP12BINDINGQSSERVICE_EXCEPTION = e;
    }

    public SBBCBGestionCuentaCuposService() {
        super(__getWsdlLocation(), SBBCBGESTIONCUENTACUPOSSOAP12BINDINGQSSERVICE_QNAME);
    }

    public SBBCBGestionCuentaCuposService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SBBCBGESTIONCUENTACUPOSSOAP12BINDINGQSSERVICE_QNAME, features);
    }

    public SBBCBGestionCuentaCuposService(URL wsdlLocation) {
        super(wsdlLocation, SBBCBGESTIONCUENTACUPOSSOAP12BINDINGQSSERVICE_QNAME);
    }

    public SBBCBGestionCuentaCuposService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SBBCBGESTIONCUENTACUPOSSOAP12BINDINGQSSERVICE_QNAME, features);
    }

    public SBBCBGestionCuentaCuposService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SBBCBGestionCuentaCuposService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SBBCBGestionCuentaCupos
     */
    @WebEndpoint(name = "SBB_CB_GestionCuentaCuposSOAP12BindingQSPort")
    public SBBCBGestionCuentaCupos getSBBCBGestionCuentaCuposSOAP12BindingQSPort() {
        return super.getPort(new QName("https://www.supernotariado.gov.co/services/bachue/cb/gestioncuentacupos/v1", "SBB_CB_GestionCuentaCuposSOAP12BindingQSPort"), SBBCBGestionCuentaCupos.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SBBCBGestionCuentaCupos
     */
    @WebEndpoint(name = "SBB_CB_GestionCuentaCuposSOAP12BindingQSPort")
    public SBBCBGestionCuentaCupos getSBBCBGestionCuentaCuposSOAP12BindingQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.supernotariado.gov.co/services/bachue/cb/gestioncuentacupos/v1", "SBB_CB_GestionCuentaCuposSOAP12BindingQSPort"), SBBCBGestionCuentaCupos.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SBBCBGESTIONCUENTACUPOSSOAP12BINDINGQSSERVICE_EXCEPTION!= null) {
            throw SBBCBGESTIONCUENTACUPOSSOAP12BINDINGQSSERVICE_EXCEPTION;
        }
        return SBBCBGESTIONCUENTACUPOSSOAP12BINDINGQSSERVICE_WSDL_LOCATION;
    }

}
