
package co.gov.supernotariado.bachue.clientebus.servicios;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import co.gov.supernotariado.bachue.clientebus.consultadatosbasicos.operacion.SBBEEDatosBasicosMatricula;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SBB_EE_DatosBasicosMatriculaQSService", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/ee/datosBasicosMatricula/v1", wsdlLocation = "http://localhost/wsdl/SBB_EE_DatosBasicosMatricula.wsdl")
public class SBBEEDatosBasicosMatriculaService
    extends Service
{

    private final static URL SBBEEDATOSBASICOSMATRICULAQSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SBBEEDATOSBASICOSMATRICULAQSSERVICE_EXCEPTION;
    private final static QName SBBEEDATOSBASICOSMATRICULAQSSERVICE_QNAME = new QName("https://www.supernotariado.gov.co/services/bachue/ee/datosBasicosMatricula/v1", "SBB_EE_DatosBasicosMatriculaQSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/wsdl/SBB_EE_DatosBasicosMatricula.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SBBEEDATOSBASICOSMATRICULAQSSERVICE_WSDL_LOCATION = url;
        SBBEEDATOSBASICOSMATRICULAQSSERVICE_EXCEPTION = e;
    }

    public SBBEEDatosBasicosMatriculaService() {
        super(__getWsdlLocation(), SBBEEDATOSBASICOSMATRICULAQSSERVICE_QNAME);
    }

    public SBBEEDatosBasicosMatriculaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SBBEEDATOSBASICOSMATRICULAQSSERVICE_QNAME, features);
    }

    public SBBEEDatosBasicosMatriculaService(URL wsdlLocation) {
        super(wsdlLocation, SBBEEDATOSBASICOSMATRICULAQSSERVICE_QNAME);
    }

    public SBBEEDatosBasicosMatriculaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SBBEEDATOSBASICOSMATRICULAQSSERVICE_QNAME, features);
    }

    public SBBEEDatosBasicosMatriculaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SBBEEDatosBasicosMatriculaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SBBEEDatosBasicosMatricula
     */
    @WebEndpoint(name = "SBB_EE_DatosBasicosMatriculaQSPort")
    public SBBEEDatosBasicosMatricula getSBBEEDatosBasicosMatriculaQSPort() {
        return super.getPort(new QName("https://www.supernotariado.gov.co/services/bachue/ee/datosBasicosMatricula/v1", "SBB_EE_DatosBasicosMatriculaQSPort"), SBBEEDatosBasicosMatricula.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SBBEEDatosBasicosMatricula
     */
    @WebEndpoint(name = "SBB_EE_DatosBasicosMatriculaQSPort")
    public SBBEEDatosBasicosMatricula getSBBEEDatosBasicosMatriculaQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.supernotariado.gov.co/services/bachue/ee/datosBasicosMatricula/v1", "SBB_EE_DatosBasicosMatriculaQSPort"), SBBEEDatosBasicosMatricula.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SBBEEDATOSBASICOSMATRICULAQSSERVICE_EXCEPTION!= null) {
            throw SBBEEDATOSBASICOSMATRICULAQSSERVICE_EXCEPTION;
        }
        return SBBEEDATOSBASICOSMATRICULAQSSERVICE_WSDL_LOCATION;
    }

}