
package co.gov.supernotariado.bachue.clientebus.servicios;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import co.gov.supernotariado.bachue.clientebus.operacionesfinancieras.operacion.SBBEFOperacionesFinancieras;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SBB_EF_OperacionesFinancierasSOAP12BindingQSService", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/ef/operacionesfinancieras/v2", wsdlLocation = "http://localhost/wsdl/operacionesfinancieras.wsdl")
public class SBBEFOperacionesFinancierasService
    extends Service
{

    private final static URL SBBEFOPERACIONESFINANCIERASSOAP12BINDINGQSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SBBEFOPERACIONESFINANCIERASSOAP12BINDINGQSSERVICE_EXCEPTION;
    private final static QName SBBEFOPERACIONESFINANCIERASSOAP12BINDINGQSSERVICE_QNAME = new QName("https://www.supernotariado.gov.co/services/bachue/ef/operacionesfinancieras/v2", "SBB_EF_OperacionesFinancierasSOAP12BindingQSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/wsdl/operacionesfinancieras.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SBBEFOPERACIONESFINANCIERASSOAP12BINDINGQSSERVICE_WSDL_LOCATION = url;
        SBBEFOPERACIONESFINANCIERASSOAP12BINDINGQSSERVICE_EXCEPTION = e;
    }

    public SBBEFOperacionesFinancierasService() {
        super(__getWsdlLocation(), SBBEFOPERACIONESFINANCIERASSOAP12BINDINGQSSERVICE_QNAME);
    }

    public SBBEFOperacionesFinancierasService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SBBEFOPERACIONESFINANCIERASSOAP12BINDINGQSSERVICE_QNAME, features);
    }

    public SBBEFOperacionesFinancierasService(URL wsdlLocation) {
        super(wsdlLocation, SBBEFOPERACIONESFINANCIERASSOAP12BINDINGQSSERVICE_QNAME);
    }

    public SBBEFOperacionesFinancierasService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SBBEFOPERACIONESFINANCIERASSOAP12BINDINGQSSERVICE_QNAME, features);
    }

    public SBBEFOperacionesFinancierasService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SBBEFOperacionesFinancierasService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SBBEFOperacionesFinancieras
     */
    @WebEndpoint(name = "SBB_EF_OperacionesFinancierasSOAP12BindingQSPort")
    public SBBEFOperacionesFinancieras getSBBEFOperacionesFinancierasSOAP12BindingQSPort() {
        return super.getPort(new QName("https://www.supernotariado.gov.co/services/bachue/ef/operacionesfinancieras/v2", "SBB_EF_OperacionesFinancierasSOAP12BindingQSPort"), SBBEFOperacionesFinancieras.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SBBEFOperacionesFinancieras
     */
    @WebEndpoint(name = "SBB_EF_OperacionesFinancierasSOAP12BindingQSPort")
    public SBBEFOperacionesFinancieras getSBBEFOperacionesFinancierasSOAP12BindingQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.supernotariado.gov.co/services/bachue/ef/operacionesfinancieras/v2", "SBB_EF_OperacionesFinancierasSOAP12BindingQSPort"), SBBEFOperacionesFinancieras.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SBBEFOPERACIONESFINANCIERASSOAP12BINDINGQSSERVICE_EXCEPTION!= null) {
            throw SBBEFOPERACIONESFINANCIERASSOAP12BINDINGQSSERVICE_EXCEPTION;
        }
        return SBBEFOPERACIONESFINANCIERASSOAP12BINDINGQSSERVICE_WSDL_LOCATION;
    }

}
