package co.gov.supernotariado.bachue.clientebus.servicios;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import co.gov.supernotariado.bachue.clientebus.consultapazysalvotributario.operacion.SBBEEConsultaPazySalvoTributario;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SBB_EE_ConsultaPazySalvoTributarioSOAP12BindingQSService", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/ee/consultapazysalvotributario/v1", wsdlLocation = "http://localhost/wsdl/consultarpazysalvotributario.wsdl")
public class SBBEEConsultaPazySalvoTributarioService
    extends Service
{

    private final static URL SBBEECONSULTAPAZYSALVOTRIBUTARIOSOAP12BINDINGQSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SBBEECONSULTAPAZYSALVOTRIBUTARIOSOAP12BINDINGQSSERVICE_EXCEPTION;
    private final static QName SBBEECONSULTAPAZYSALVOTRIBUTARIOSOAP12BINDINGQSSERVICE_QNAME = new QName("https://www.supernotariado.gov.co/services/bachue/ee/consultapazysalvotributario/v1", "SBB_EE_ConsultaPazySalvoTributarioSOAP12BindingQSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/wsdl/consultarpazysalvotributario.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SBBEECONSULTAPAZYSALVOTRIBUTARIOSOAP12BINDINGQSSERVICE_WSDL_LOCATION = url;
        SBBEECONSULTAPAZYSALVOTRIBUTARIOSOAP12BINDINGQSSERVICE_EXCEPTION = e;
    }

    public SBBEEConsultaPazySalvoTributarioService() {
        super(__getWsdlLocation(), SBBEECONSULTAPAZYSALVOTRIBUTARIOSOAP12BINDINGQSSERVICE_QNAME);
    }

    public SBBEEConsultaPazySalvoTributarioService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SBBEECONSULTAPAZYSALVOTRIBUTARIOSOAP12BINDINGQSSERVICE_QNAME, features);
    }

    public SBBEEConsultaPazySalvoTributarioService(URL wsdlLocation) {
        super(wsdlLocation, SBBEECONSULTAPAZYSALVOTRIBUTARIOSOAP12BINDINGQSSERVICE_QNAME);
    }

    public SBBEEConsultaPazySalvoTributarioService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SBBEECONSULTAPAZYSALVOTRIBUTARIOSOAP12BINDINGQSSERVICE_QNAME, features);
    }

    public SBBEEConsultaPazySalvoTributarioService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SBBEEConsultaPazySalvoTributarioService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SBBEEConsultaPazySalvoTributario
     */
    @WebEndpoint(name = "SBB_EE_ConsultaPazySalvoTributarioSOAP12BindingQSPort")
    public SBBEEConsultaPazySalvoTributario getSBBEEConsultaPazySalvoTributarioSOAP12BindingQSPort() {
        return super.getPort(new QName("https://www.supernotariado.gov.co/services/bachue/ee/consultapazysalvotributario/v1", "SBB_EE_ConsultaPazySalvoTributarioSOAP12BindingQSPort"), SBBEEConsultaPazySalvoTributario.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SBBEEConsultaPazySalvoTributario
     */
    @WebEndpoint(name = "SBB_EE_ConsultaPazySalvoTributarioSOAP12BindingQSPort")
    public SBBEEConsultaPazySalvoTributario getSBBEEConsultaPazySalvoTributarioSOAP12BindingQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.supernotariado.gov.co/services/bachue/ee/consultapazysalvotributario/v1", "SBB_EE_ConsultaPazySalvoTributarioSOAP12BindingQSPort"), SBBEEConsultaPazySalvoTributario.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SBBEECONSULTAPAZYSALVOTRIBUTARIOSOAP12BINDINGQSSERVICE_EXCEPTION!= null) {
            throw SBBEECONSULTAPAZYSALVOTRIBUTARIOSOAP12BINDINGQSSERVICE_EXCEPTION;
        }
        return SBBEECONSULTAPAZYSALVOTRIBUTARIOSOAP12BINDINGQSSERVICE_WSDL_LOCATION;
    }

}
