
package co.gov.supernotariado.bachue.clientebus.servicios;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import co.gov.supernotariado.bachue.clientebus.consultarhistorialsolicitudespagadas.operacion.SBBEEConsultaHistorialSolicitudesPagadas;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SBB_EE_ConsultaHistorialSolicitudesPagadasSOAP12BindingQSService", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/ee/consultahistorialsolicitudespagadas/v1", wsdlLocation = "http://localhost/wsdl/consultarhistorialsolicitudespagadas.wsdl")
public class SBBEEConsultaHistorialSolicitudesPagadasService
    extends Service
{

    private final static URL SBBEECONSULTAHISTORIALSOLICITUDESPAGADASSOAP12BINDINGQSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SBBEECONSULTAHISTORIALSOLICITUDESPAGADASSOAP12BINDINGQSSERVICE_EXCEPTION;
    private final static QName SBBEECONSULTAHISTORIALSOLICITUDESPAGADASSOAP12BINDINGQSSERVICE_QNAME = new QName("https://www.supernotariado.gov.co/services/bachue/ee/consultahistorialsolicitudespagadas/v1", "SBB_EE_ConsultaHistorialSolicitudesPagadasSOAP12BindingQSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/wsdl/consultarhistorialsolicitudespagadas.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SBBEECONSULTAHISTORIALSOLICITUDESPAGADASSOAP12BINDINGQSSERVICE_WSDL_LOCATION = url;
        SBBEECONSULTAHISTORIALSOLICITUDESPAGADASSOAP12BINDINGQSSERVICE_EXCEPTION = e;
    }

    public SBBEEConsultaHistorialSolicitudesPagadasService() {
        super(__getWsdlLocation(), SBBEECONSULTAHISTORIALSOLICITUDESPAGADASSOAP12BINDINGQSSERVICE_QNAME);
    }

    public SBBEEConsultaHistorialSolicitudesPagadasService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SBBEECONSULTAHISTORIALSOLICITUDESPAGADASSOAP12BINDINGQSSERVICE_QNAME, features);
    }

    public SBBEEConsultaHistorialSolicitudesPagadasService(URL wsdlLocation) {
        super(wsdlLocation, SBBEECONSULTAHISTORIALSOLICITUDESPAGADASSOAP12BINDINGQSSERVICE_QNAME);
    }

    public SBBEEConsultaHistorialSolicitudesPagadasService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SBBEECONSULTAHISTORIALSOLICITUDESPAGADASSOAP12BINDINGQSSERVICE_QNAME, features);
    }

    public SBBEEConsultaHistorialSolicitudesPagadasService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SBBEEConsultaHistorialSolicitudesPagadasService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SBBEEConsultaHistorialSolicitudesPagadas
     */
    @WebEndpoint(name = "SBB_EE_ConsultaHistorialSolicitudesPagadasSOAP12BindingQSPort")
    public SBBEEConsultaHistorialSolicitudesPagadas getSBBEEConsultaHistorialSolicitudesPagadasSOAP12BindingQSPort() {
        return super.getPort(new QName("https://www.supernotariado.gov.co/services/bachue/ee/consultahistorialsolicitudespagadas/v1", "SBB_EE_ConsultaHistorialSolicitudesPagadasSOAP12BindingQSPort"), SBBEEConsultaHistorialSolicitudesPagadas.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SBBEEConsultaHistorialSolicitudesPagadas
     */
    @WebEndpoint(name = "SBB_EE_ConsultaHistorialSolicitudesPagadasSOAP12BindingQSPort")
    public SBBEEConsultaHistorialSolicitudesPagadas getSBBEEConsultaHistorialSolicitudesPagadasSOAP12BindingQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.supernotariado.gov.co/services/bachue/ee/consultahistorialsolicitudespagadas/v1", "SBB_EE_ConsultaHistorialSolicitudesPagadasSOAP12BindingQSPort"), SBBEEConsultaHistorialSolicitudesPagadas.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SBBEECONSULTAHISTORIALSOLICITUDESPAGADASSOAP12BINDINGQSSERVICE_EXCEPTION!= null) {
            throw SBBEECONSULTAHISTORIALSOLICITUDESPAGADASSOAP12BINDINGQSSERVICE_EXCEPTION;
        }
        return SBBEECONSULTAHISTORIALSOLICITUDESPAGADASSOAP12BINDINGQSSERVICE_WSDL_LOCATION;
    }

}
