
package co.gov.supernotariado.bachue.clientebus.servicios;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import co.gov.supernotariado.bachue.clientebus.gestionalertastitulares.operacion.SDIEEGestionAlertasTitulares;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SDI_EE_GestionAlertasTitularesSOAP12BindingQSService", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/ee/gestionalertastitulares/v1", wsdlLocation = "http://localhost/wsdl/gestionalertastitulares.wsdl")
public class SDIEEGestionAlertasTitularesService
    extends Service
{

    private final static URL SDIEEGESTIONALERTASTITULARESSOAP12BINDINGQSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SDIEEGESTIONALERTASTITULARESSOAP12BINDINGQSSERVICE_EXCEPTION;
    private final static QName SDIEEGESTIONALERTASTITULARESSOAP12BINDINGQSSERVICE_QNAME = new QName("https://www.supernotariado.gov.co/services/bachue/ee/gestionalertastitulares/v1", "SDI_EE_GestionAlertasTitularesSOAP12BindingQSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/wsdl/gestionalertastitulares.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SDIEEGESTIONALERTASTITULARESSOAP12BINDINGQSSERVICE_WSDL_LOCATION = url;
        SDIEEGESTIONALERTASTITULARESSOAP12BINDINGQSSERVICE_EXCEPTION = e;
    }

    public SDIEEGestionAlertasTitularesService() {
        super(__getWsdlLocation(), SDIEEGESTIONALERTASTITULARESSOAP12BINDINGQSSERVICE_QNAME);
    }

    public SDIEEGestionAlertasTitularesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SDIEEGESTIONALERTASTITULARESSOAP12BINDINGQSSERVICE_QNAME, features);
    }

    public SDIEEGestionAlertasTitularesService(URL wsdlLocation) {
        super(wsdlLocation, SDIEEGESTIONALERTASTITULARESSOAP12BINDINGQSSERVICE_QNAME);
    }

    public SDIEEGestionAlertasTitularesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SDIEEGESTIONALERTASTITULARESSOAP12BINDINGQSSERVICE_QNAME, features);
    }

    public SDIEEGestionAlertasTitularesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SDIEEGestionAlertasTitularesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SDIEEGestionAlertasTitulares
     */
    @WebEndpoint(name = "SDI_EE_GestionAlertasTitularesSOAP12BindingQSPort")
    public SDIEEGestionAlertasTitulares getSDIEEGestionAlertasTitularesSOAP12BindingQSPort() {
        return super.getPort(new QName("https://www.supernotariado.gov.co/services/bachue/ee/gestionalertastitulares/v1", "SDI_EE_GestionAlertasTitularesSOAP12BindingQSPort"), SDIEEGestionAlertasTitulares.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SDIEEGestionAlertasTitulares
     */
    @WebEndpoint(name = "SDI_EE_GestionAlertasTitularesSOAP12BindingQSPort")
    public SDIEEGestionAlertasTitulares getSDIEEGestionAlertasTitularesSOAP12BindingQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.supernotariado.gov.co/services/bachue/ee/gestionalertastitulares/v1", "SDI_EE_GestionAlertasTitularesSOAP12BindingQSPort"), SDIEEGestionAlertasTitulares.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SDIEEGESTIONALERTASTITULARESSOAP12BINDINGQSSERVICE_EXCEPTION!= null) {
            throw SDIEEGESTIONALERTASTITULARESSOAP12BINDINGQSSERVICE_EXCEPTION;
        }
        return SDIEEGESTIONALERTASTITULARESSOAP12BINDINGQSSERVICE_WSDL_LOCATION;
    }

}
