
package co.gov.supernotariado.bachue.clientebus.servicios;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import co.gov.supernotariado.bachue.clientebus.enviodocumento.operacion.SUTCOEnvioDocumentos;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SUT_CO_EnvioDocumentos", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/co/enviodocumentos/v1", wsdlLocation = "http://localhost/wsdl/SUT_CO_EnvioDocumentos.wsdl")
public class SUTCOEnvioDocumentosService
    extends Service
{

    private final static URL SUTCOENVIODOCUMENTOS_WSDL_LOCATION;
    private final static WebServiceException SUTCOENVIODOCUMENTOS_EXCEPTION;
    private final static QName SUTCOENVIODOCUMENTOS_QNAME = new QName("https://www.supernotariado.gov.co/services/bachue/co/enviodocumentos/v1", "SUT_CO_EnvioDocumentos");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/wsdl/SUT_CO_EnvioDocumentos.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SUTCOENVIODOCUMENTOS_WSDL_LOCATION = url;
        SUTCOENVIODOCUMENTOS_EXCEPTION = e;
    }

    public SUTCOEnvioDocumentosService() {
        super(__getWsdlLocation(), SUTCOENVIODOCUMENTOS_QNAME);
    }

    public SUTCOEnvioDocumentosService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUTCOENVIODOCUMENTOS_QNAME, features);
    }

    public SUTCOEnvioDocumentosService(URL wsdlLocation) {
        super(wsdlLocation, SUTCOENVIODOCUMENTOS_QNAME);
    }

    public SUTCOEnvioDocumentosService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUTCOENVIODOCUMENTOS_QNAME, features);
    }

    public SUTCOEnvioDocumentosService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SUTCOEnvioDocumentosService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SUTCOEnvioDocumentos
     */
    @WebEndpoint(name = "SUT_CO_EnvioDocumentosPort")
    public SUTCOEnvioDocumentos getSUTCOEnvioDocumentosPort() {
        return super.getPort(new QName("https://www.supernotariado.gov.co/services/bachue/co/enviodocumentos/v1", "SUT_CO_EnvioDocumentosPort"), SUTCOEnvioDocumentos.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SUTCOEnvioDocumentos
     */
    @WebEndpoint(name = "SUT_CO_EnvioDocumentosPort")
    public SUTCOEnvioDocumentos getSUTCOEnvioDocumentosPort(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.supernotariado.gov.co/services/bachue/co/enviodocumentos/v1", "SUT_CO_EnvioDocumentosPort"), SUTCOEnvioDocumentos.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SUTCOENVIODOCUMENTOS_EXCEPTION!= null) {
            throw SUTCOENVIODOCUMENTOS_EXCEPTION;
        }
        return SUTCOENVIODOCUMENTOS_WSDL_LOCATION;
    }

}
