
package co.gov.supernotariado.bachue.clientebus.servicios;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import co.gov.supernotariado.bachue.clientebus.controldigitalizacion.operacion.SUTCIControlDigitalizacion;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SUT_CI_ControlDigitalizacionSOAP12BindingQSService", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/ci/controldigitalizacion/v1", wsdlLocation = "http://localhost/wsdl/controldigitalizacion.wsdl")
public class SUTCIControlDigitalizacionService
    extends Service
{

    private final static URL SUTCICONTROLDIGITALIZACIONSOAP12BINDINGQSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SUTCICONTROLDIGITALIZACIONSOAP12BINDINGQSSERVICE_EXCEPTION;
    private final static QName SUTCICONTROLDIGITALIZACIONSOAP12BINDINGQSSERVICE_QNAME = new QName("https://www.supernotariado.gov.co/services/bachue/ci/controldigitalizacion/v1", "SUT_CI_ControlDigitalizacionSOAP12BindingQSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/wsdl/controldigitalizacion.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SUTCICONTROLDIGITALIZACIONSOAP12BINDINGQSSERVICE_WSDL_LOCATION = url;
        SUTCICONTROLDIGITALIZACIONSOAP12BINDINGQSSERVICE_EXCEPTION = e;
    }

    public SUTCIControlDigitalizacionService() {
        super(__getWsdlLocation(), SUTCICONTROLDIGITALIZACIONSOAP12BINDINGQSSERVICE_QNAME);
    }

    public SUTCIControlDigitalizacionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUTCICONTROLDIGITALIZACIONSOAP12BINDINGQSSERVICE_QNAME, features);
    }

    public SUTCIControlDigitalizacionService(URL wsdlLocation) {
        super(wsdlLocation, SUTCICONTROLDIGITALIZACIONSOAP12BINDINGQSSERVICE_QNAME);
    }

    public SUTCIControlDigitalizacionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUTCICONTROLDIGITALIZACIONSOAP12BINDINGQSSERVICE_QNAME, features);
    }

    public SUTCIControlDigitalizacionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SUTCIControlDigitalizacionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SUTCIControlDigitalizacion
     */
    @WebEndpoint(name = "SUT_CI_ControlDigitalizacionSOAP12BindingQSPort")
    public SUTCIControlDigitalizacion getSUTCIControlDigitalizacionSOAP12BindingQSPort() {
        return super.getPort(new QName("https://www.supernotariado.gov.co/services/bachue/ci/controldigitalizacion/v1", "SUT_CI_ControlDigitalizacionSOAP12BindingQSPort"), SUTCIControlDigitalizacion.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SUTCIControlDigitalizacion
     */
    @WebEndpoint(name = "SUT_CI_ControlDigitalizacionSOAP12BindingQSPort")
    public SUTCIControlDigitalizacion getSUTCIControlDigitalizacionSOAP12BindingQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.supernotariado.gov.co/services/bachue/ci/controldigitalizacion/v1", "SUT_CI_ControlDigitalizacionSOAP12BindingQSPort"), SUTCIControlDigitalizacion.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SUTCICONTROLDIGITALIZACIONSOAP12BINDINGQSSERVICE_EXCEPTION!= null) {
            throw SUTCICONTROLDIGITALIZACIONSOAP12BINDINGQSSERVICE_EXCEPTION;
        }
        return SUTCICONTROLDIGITALIZACIONSOAP12BINDINGQSSERVICE_WSDL_LOCATION;
    }

}
