package co.gov.supernotariado.bachue.clientebus.operacionesfinancieras.operacion;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import co.gov.supernotariado.bachue.clientebus.operacionesfinancieras.types.actualizardatossolicitantes.ActualizarDatosSolicitantesObjectFactory;
import co.gov.supernotariado.bachue.clientebus.operacionesfinancieras.types.actualizardatossolicitantes.TipoEntradaActualizarDatosSolicitante;
import co.gov.supernotariado.bachue.clientebus.operacionesfinancieras.types.actualizardatossolicitantes.TipoSalidaActualizarDatosSolicitante;
import co.gov.supernotariado.bachue.clientebus.operacionesfinancieras.types.consultarestadoliquidacion.ConsultarEstadoLiquidacionObjectFactory;
import co.gov.supernotariado.bachue.clientebus.operacionesfinancieras.types.consultarestadoliquidacion.TipoEntradaConsultarEstadoLiquidacion;
import co.gov.supernotariado.bachue.clientebus.operacionesfinancieras.types.consultarestadoliquidacion.TipoSalidaConsultarEstadoLiquidacion;
import co.gov.supernotariado.bachue.clientebus.operacionesfinancieras.types.consultartarifaservicio.ConsultarTarifaServicioObjectFactory;
import co.gov.supernotariado.bachue.clientebus.operacionesfinancieras.types.consultartarifaservicio.TipoEntradaConsultarTarifaServicio;
import co.gov.supernotariado.bachue.clientebus.operacionesfinancieras.types.consultartarifaservicio.TipoSalidaConsultarTarifaServicio;
import co.gov.supernotariado.bachue.clientebus.operacionesfinancieras.types.generarliquidacion.GenerarLiquidacionObjectFactory;
import co.gov.supernotariado.bachue.clientebus.operacionesfinancieras.types.generarliquidacion.TipoEntradaGenerarLiquidacion;
import co.gov.supernotariado.bachue.clientebus.operacionesfinancieras.types.generarliquidacion.TipoSalidaGenerarLiquidacion;
import co.gov.supernotariado.bachue.clientebus.operacionesfinancieras.types.notificarpago.NotificarPagoObjectFactory;
import co.gov.supernotariado.bachue.clientebus.operacionesfinancieras.types.notificarpago.TipoEntradaNotificarPago;
import co.gov.supernotariado.bachue.clientebus.operacionesfinancieras.types.notificarpago.TipoSalidaNotificarPago;
import co.gov.supernotariado.bachue.clientebus.operacionesfinancieras.types.obtenerpdfliquidacion.ObtenerPdfLiquidacionObjectFactory;
import co.gov.supernotariado.bachue.clientebus.operacionesfinancieras.types.obtenerpdfliquidacion.TipoEntradaObtenerPDFLiquidacion;
import co.gov.supernotariado.bachue.clientebus.operacionesfinancieras.types.obtenerpdfliquidacion.TipoSalidaObtenerPDFLiquidacion;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SBB_EF_OperacionesFinancieras", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/ef/operacionesfinancieras/v2")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
	ActualizarDatosSolicitantesObjectFactory.class,
	ConsultarEstadoLiquidacionObjectFactory.class,
	ConsultarTarifaServicioObjectFactory.class,
	GenerarLiquidacionObjectFactory.class,
	NotificarPagoObjectFactory.class,
	ObtenerPdfLiquidacionObjectFactory.class
})
public interface SBBEFOperacionesFinancieras {


    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.ef.operacionesfinancieras.consultarestadoliquidacion.v2.TipoSalidaConsultarEstadoLiquidacion
     */
    @WebMethod(operationName = "ConsultarEstadoLiquidacion", action = "https://www.supernotariado.gov.co/services/bachue/ef/operacionesfinancieras/v2/ConsultarEstadoLiquidacion")
    @WebResult(name = "salidaConsultarEstadoLiquidacion", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ef/operacionesfinancieras/consultarestadoliquidacion/v2", partName = "salida")
    public TipoSalidaConsultarEstadoLiquidacion consultarEstadoLiquidacion(
        @WebParam(name = "entradaConsultarEstadoLiquidacion", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ef/operacionesfinancieras/consultarestadoliquidacion/v2", partName = "entrada")
        TipoEntradaConsultarEstadoLiquidacion entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.ef.operacionesfinancieras.consultartarifaservicio.v2.TipoSalidaConsultarTarifaServicio
     */
    @WebMethod(operationName = "ConsultarTarifaServicio", action = "https://www.supernotariado.gov.co/services/bachue/ef/operacionesfinancieras/v2/ConsultarTarifaServicio")
    @WebResult(name = "salidaConsultarTarifaServicio", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ef/operacionesfinancieras/consultartarifaservicio/v2", partName = "salida")
    public TipoSalidaConsultarTarifaServicio consultarTarifaServicio(
        @WebParam(name = "entradaConsultarTarifaServicio", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ef/operacionesfinancieras/consultartarifaservicio/v2", partName = "entrada")
        TipoEntradaConsultarTarifaServicio entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.ef.operacionesfinancieras.generarliquidacion.v2.TipoSalidaGenerarLiquidacion
     */
    @WebMethod(operationName = "GenerarLiquidacion", action = "https://www.supernotariado.gov.co/services/bachue/ef/operacionesfinancieras/v2/GenerarLiquidacion")
    @WebResult(name = "salidaGenerarLiquidacion", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ef/operacionesfinancieras/generarliquidacion/v2", partName = "salida")
    public TipoSalidaGenerarLiquidacion generarLiquidacion(
        @WebParam(name = "entradaGenerarLiquidacion", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ef/operacionesfinancieras/generarliquidacion/v2", partName = "entrada")
        TipoEntradaGenerarLiquidacion entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.ef.operacionesfinancieras.notificarpago.v2.TipoSalidaNotificarPago
     */
    @WebMethod(operationName = "NotificarPago", action = "https://www.supernotariado.gov.co/services/bachue/ef/operacionesfinancieras/v2/NotificarPago")
    @WebResult(name = "salidaNotificarPago", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ef/operacionesfinancieras/notificarpago/v2", partName = "salida")
    public TipoSalidaNotificarPago notificarPago(
        @WebParam(name = "entradaNotificarPago", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ef/operacionesfinancieras/notificarpago/v2", partName = "entrada")
        TipoEntradaNotificarPago entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.ef.operacionesfinancieras.obtenerpdfliquidacion.v2.TipoSalidaObtenerPDFLiquidacion
     */
    @WebMethod(operationName = "ObtenerPDFLiquidacion", action = "https://www.supernotariado.gov.co/services/bachue/ef/operacionesfinancieras/v2/ObtenerPDFLiquidacion")
    @WebResult(name = "salidaObtenerPDFLiquidacion", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ef/operacionesfinancieras/obtenerpdfliquidacion/v2", partName = "salida")
    public TipoSalidaObtenerPDFLiquidacion obtenerPDFLiquidacion(
        @WebParam(name = "entradaObtenerPDFLiquidacion", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ef/operacionesfinancieras/obtenerpdfliquidacion/v2", partName = "entrada")
        TipoEntradaObtenerPDFLiquidacion entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.ef.operacionesfinancieras.actualizardatossolicitante.v2.TipoSalidaActualizarDatosSolicitante
     */
    @WebMethod(operationName = "ActualizarDatosSolicitante", action = "https://www.supernotariado.gov.co/services/bachue/ef/operacionesfinancieras/v2/ActualizarDatosSolicitante")
    @WebResult(name = "salidaActualizarDatosSolicitante", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ef/operacionesfinancieras/actualizardatossolicitante/v2", partName = "salida")
    public TipoSalidaActualizarDatosSolicitante actualizarDatosSolicitante(
        @WebParam(name = "entradaActualizarDatosSolicitante", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ef/operacionesfinancieras/actualizardatossolicitante/v2", partName = "entrada")
        TipoEntradaActualizarDatosSolicitante entrada);

}
