
package co.gov.supernotariado.bachue.clientebus.consultapazysalvotributario.operacion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import co.gov.supernotariado.bachue.clientebus.consultapazysalvotributario.types.consultarpazysalvotributario.ConsultarPazySalvoTributarioObjectFactory;
import co.gov.supernotariado.bachue.clientebus.consultapazysalvotributario.types.consultarpazysalvotributario.TipoEntradaConsultarPazySalvoTributario;
import co.gov.supernotariado.bachue.clientebus.consultapazysalvotributario.types.consultarpazysalvotributario.TipoSalidaConsultarPazySalvoTributario;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SBB_EE_ConsultaPazySalvoTributario", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/ee/consultapazysalvotributario/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
	ConsultarPazySalvoTributarioObjectFactory.class
})
public interface SBBEEConsultaPazySalvoTributario {


    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.ee.consultapazysalvotributario.consultarpazysalvotributario.v1.TipoSalidaConsultarPazySalvoTributario
     */
    @WebMethod(operationName = "ConsultarPazySalvoTributario", action = "https://www.supernotariado.gov.co/services/bachue/cb/consultapazysalvotributario/v1/ConsultarPazySalvoTributario")
    @WebResult(name = "salidaConsultarPazySalvoTributario", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ee/consultapazysalvotributario/consultarpazysalvotributario/v1", partName = "salida")
    public TipoSalidaConsultarPazySalvoTributario consultarPazySalvoTributario(
        @WebParam(name = "entradaConsultarPazySalvoTributario", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ee/consultapazysalvotributario/consultarpazysalvotributario/v1", partName = "entrada")
        TipoEntradaConsultarPazySalvoTributario entrada);

}
