
package co.gov.supernotariado.bachue.clientebus.consultamigracion.operacion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import co.gov.supernotariado.bachue.clientebus.consultamigracion.types.consultarmigracionmatriculas.ConsultarMigracionMatriculasObjectFactory;
import co.gov.supernotariado.bachue.clientebus.consultamigracion.types.consultarmigracionmatriculas.TipoEntradaConsultaMigracionMatriculas;
import co.gov.supernotariado.bachue.clientebus.consultamigracion.types.consultarmigracionmatriculas.TipoSalidaConsultaMigracionMatriculas;
import co.gov.supernotariado.bachue.clientebus.consultamigracion.types.consultarmigracionorip.ConsultarMigracionOripObjectFactory;
import co.gov.supernotariado.bachue.clientebus.consultamigracion.types.consultarmigracionorip.TipoEntradaConsultaMigracionORIP;
import co.gov.supernotariado.bachue.clientebus.consultamigracion.types.consultarmigracionorip.TipoSalidaConsultaMigracionORIP;
import co.gov.supernotariado.bachue.clientebus.consultamigracion.types.consultarmigracionpredio.ConsultarMigracionPredioObjectFactory;
import co.gov.supernotariado.bachue.clientebus.consultamigracion.types.consultarmigracionpredio.TipoEntradaConsultaMigracionPredio;
import co.gov.supernotariado.bachue.clientebus.consultamigracion.types.consultarmigracionpredio.TipoSalidaConsultaMigracionPredio;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SUT_CB_ConsultaMigracion", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/cb/consultamigracion/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
	ConsultarMigracionMatriculasObjectFactory.class,
	ConsultarMigracionOripObjectFactory.class,
	ConsultarMigracionPredioObjectFactory.class
})
public interface SUTCBConsultaMigracion {


    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.services.bachue.cb.consultamigracion.consultarmigracionpredio.v1.TipoSalidaConsultaMigracionPredio
     */
    @WebMethod(action = "https://www.supernotariado.gov.co/services/bachue/cb/consultamigracion/v1/consultarMigracionPredio")
    @WebResult(name = "salidaConsultaMigracionPredio", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/cb/consultamigracion/consultarMigracionPredio/v1", partName = "salida")
    public TipoSalidaConsultaMigracionPredio consultarMigracionPredio(
        @WebParam(name = "entradaConsultaMigracionPredio", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/cb/consultamigracion/consultarMigracionPredio/v1", partName = "entrada")
        TipoEntradaConsultaMigracionPredio entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.services.bachue.cb.consultamigracion.consultarmigracionorip.v1.TipoSalidaConsultaMigracionORIP
     */
    @WebMethod(action = "https://www.supernotariado.gov.co/services/bachue/cb/consultamigracion/v1/consultarMigracionORIP")
    @WebResult(name = "salidaConsultaMigracionORIP", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/cb/consultamigracion/consultarMigracionORIP/v1", partName = "salida")
    public TipoSalidaConsultaMigracionORIP consultarMigracionORIP(
        @WebParam(name = "entradaConsultaMigracionORIP", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/cb/consultamigracion/consultarMigracionORIP/v1", partName = "entrada")
        TipoEntradaConsultaMigracionORIP entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.services.bachue.cb.consultamigracion.consultarmigracionmatriculas.v1.TipoSalidaConsultaMigracionMatriculas
     */
    @WebMethod(action = "https://www.supernotariado.gov.co/services/bachue/cb/consultamigracion/v1/consultarMigracionMatriculas")
    @WebResult(name = "salidaConsultaMigracionMatriculas", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/cb/consultamigracion/consultarMigracionMatriculas/v1", partName = "salida")
    public TipoSalidaConsultaMigracionMatriculas consultarMigracionMatriculas(
        @WebParam(name = "entradaConsultaMigracionMatriculas", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/cb/consultamigracion/consultarMigracionMatriculas/v1", partName = "entrada")
        TipoEntradaConsultaMigracionMatriculas entrada);

}
