
package co.gov.supernotariado.bachue.clientebus.consultatrazabilidad.operacion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import co.gov.supernotariado.bachue.clientebus.consultatrazabilidad.types.consultatrazabilidadnoc.ConsultaTrazabilidadNOCObjectFactory;
import co.gov.supernotariado.bachue.clientebus.consultatrazabilidad.types.consultatrazabilidadnoc.TipoEntradaTrazabilidadTramiteRegistroNodoCentral;
import co.gov.supernotariado.bachue.clientebus.consultatrazabilidad.types.consultatrazabilidadnoc.TipoSalidaTrazabilidadTramiteRegistroNodoCentral;
import co.gov.supernotariado.bachue.clientebus.consultatrazabilidad.types.consultaactosturno.ConsultaActosTurnoObjectFactory;
import co.gov.supernotariado.bachue.clientebus.consultatrazabilidad.types.consultaactosturno.TipoEntradaConsultaActosTurno;
import co.gov.supernotariado.bachue.clientebus.consultatrazabilidad.types.consultaactosturno.TipoSalidaConsultaActosTurno;
import co.gov.supernotariado.bachue.clientebus.consultatrazabilidad.types.consultatrazabilidad.ConsultaTrazabilidadObjectFactory;
import co.gov.supernotariado.bachue.clientebus.consultatrazabilidad.types.consultatrazabilidad.TipoEntradaConsultarTrazabilidad;
import co.gov.supernotariado.bachue.clientebus.consultatrazabilidad.types.consultatrazabilidad.TipoSalidaConsultarTrazabilidad;
import co.gov.supernotariado.bachue.clientebus.consultatrazabilidad.types.consultadetallecertificado.ConsultaDetalleCertificadoObjectFactory;
import co.gov.supernotariado.bachue.clientebus.consultatrazabilidad.types.consultadetallecertificado.TipoEntradaConsultaDetalleCertificado;
import co.gov.supernotariado.bachue.clientebus.consultatrazabilidad.types.consultadetallecertificado.TipoSalidaConsultaDetalleCertificado;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SDI_EE_ConsultaTrazabilidad", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/ee/consultatrazabilidad/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ConsultaDetalleCertificadoObjectFactory.class,
    ConsultaActosTurnoObjectFactory.class,
    ConsultaTrazabilidadNOCObjectFactory.class,
    ConsultaTrazabilidadObjectFactory.class
})
public interface SDIEEConsultaTrazabilidad {


    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.ee.consultatrazabilidad.consultartrazabilidad.v1.TipoSalidaConsultarTrazabilidad
     */
    @WebMethod(action = "https://www.supernotariado.gov.co/services/bachue/ee/consultatrazabilidad/v1/ConsultarTrazabilidad")
    @WebResult(name = "salidaConsultarTrazabilidad", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ee/consultatrazabilidad/consultartrazabilidad/v1", partName = "salida")
    public TipoSalidaConsultarTrazabilidad consultarTrazabilidad(
        @WebParam(name = "entradaConsultarTrazabilidad", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ee/consultatrazabilidad/consultartrazabilidad/v1", partName = "entrada")
        TipoEntradaConsultarTrazabilidad entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns co.gov.gobiernoenlinea.gel_xml._1_0.schemas.integracion.supernotariado.bachue.TipoSalidaTrazabilidadTramiteRegistroNodoCentral
     */
    @WebMethod(action = "http://www.gobiernoenlinea.gov.co/GEL-XML/1.0/schemas/integracion/supernotariado/bachue")
    @WebResult(name = "salidaTrazabilidadTramiteRegistroNodoCentral", targetNamespace = "http://www.gobiernoenlinea.gov.co/GEL-XML/1.0/schemas/integracion/supernotariado/bachue", partName = "salida")
    public TipoSalidaTrazabilidadTramiteRegistroNodoCentral consultarTrazabilidadNOC(
        @WebParam(name = "entradaTrazabilidadTramiteRegistroNodoCentral", targetNamespace = "http://www.gobiernoenlinea.gov.co/GEL-XML/1.0/schemas/integracion/supernotariado/bachue", partName = "entrada")
        TipoEntradaTrazabilidadTramiteRegistroNodoCentral entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.ee.consultatrazabilidad.consultaactosturno.v1.TipoSalidaConsultaActosTurno
     */
    @WebMethod(operationName = "ConsultaActosTurno", action = "https://www.supernotariado.gov.co/services/bachue/ee/consultatrazabilidad/v1/ConsultaActosTurno")
    @WebResult(name = "salidaConsultaActosTurno", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ee/consultatrazabilidad/consultaActosTurno/v1", partName = "salida")
    public TipoSalidaConsultaActosTurno consultaActosTurno(
        @WebParam(name = "entradaConsultaActosTurno", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ee/consultatrazabilidad/consultaActosTurno/v1", partName = "entrada")
        TipoEntradaConsultaActosTurno entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.ee.consultatrazabilidad.consultadetallecertificado.v1.TipoSalidaConsultaDetalleCertificado
     */
    @WebMethod(operationName = "ConsultaDetalleCertificado", action = "https://www.supernotariado.gov.co/services/bachue/ee/consultatrazabilidad/v1/ConsultaDetalleCertificado")
    @WebResult(name = "salidaConsultaDetalleCertificado", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ee/consultatrazabilidad/consultaDetalleCertificado/v1", partName = "salida")
    public TipoSalidaConsultaDetalleCertificado consultaDetalleCertificado(
        @WebParam(name = "entradaConsultaDetalleCertificado", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ee/consultatrazabilidad/consultaDetalleCertificado/v1", partName = "entrada")
        TipoEntradaConsultaDetalleCertificado entrada);

}
