package co.gov.supernotariado.bachue.sedeelectronica.common.enums;

/**
 * Enumeracion para definir el grupo de constantes para Catalogo Documental. <br>
 * Enum que detalla los parametros de tipos documentales a usar
 * 
 * @author Smartsoft Solutions S.A.S
 * @version 1.0
 */
public enum EnumParametroDocumental implements ICatalogable{
	ALERTAS_TIERRAS("TIPO_DOC_SOLICITUD_ALERTA_TIERRAS"),
	CREACION_CUENTA_CUPOS("TIPO_DOC_CREACION_CUENTA_CUPO"),
	REGISTRO_PERSONA("TIPO_DOC_REGISTRO_USUARIOS"),
	CORRECCIONES("TIPO_DOCUMENTAL_CORRECCIONES"),//Trae todas las variables 
	DEVOLUCION_REGISTRAL("TIPOS_DOCUMENTALES_RESPUESTAS_DEV_DINERO"),
	DEVOLUCION_CORRECCION_ERRADA("TIPO_DOC_DEV_DINERO_CONSIGNACION_ERRADA"),
	DEVOLUCION_CUENTA_CUPO("TIPO_DOC_DEV_DINERO_CUENTA_CUPO"),
	PRORROGA("TIPO_DOC_REQ_PRORROGA"),
	CARGUE_PODERES("TIPO_DOC_REPOSITORIO_PODERES"),
	MODIFICACION_CUENTA_CUPO("TIPO_DOC_MODIFICACION_CUENTA_CUPO"),
	CANCELACION_CUENTA_CUPO("TIPO_DOCUMENTAL_INACTIVAR_CUENTA_CUPO"),
	USO_PODER_REVOCATORIA_PARCIAL("TIPO_DOC_PODERES_REVOCATORIA_PARCIAL"),
	USO_PODER_REVOCATORIA_TOTAL("TIPO_DOC_PODERES_REVOCATORIA_TOTAL"),
	USO_PODER_SUSTITUCION("TIPO_DOC_PODERES_SUSTITUCION"),
	USO_PODER_RENUNCIA_PARCIAL("TIPO_DOC_PODERES_RENUNCIA_PARCIAL"),
	USO_PODER_RENUNCIA_TOTAL("TIPO_DOC_PODERES_RENUNCIA_TOTAL"),
	CORRECCION_NOTARIA_ORIGEN("TIPO_DOC_PODERES_CORRECCION_NOTARIA_ORIGEN"),
	SOLICITUD_CARGUE_PODER("TIPO_DOC_PODERES_SOLICITUD_CARGUE_PODER"),
	DESISTIMIENTO("TIPO_DOC_REQ_DESISTIMIENTO"),
	SUSPENSION_TEMPORAL("TIPOS_DOCUMENTALES_SUSPENSION_TERMINOS"),
	TRASLADO_MATRICULA("TIPO_DOC_REQ_TRASLADO_MATRICULAS"),
	INTERPOSICION_RECURSOS("TIPO_DOC_REQ_DESISTIMIENTO "),
	CERTIFICADOS_ESPECIALES("TIPO_DOC_SOLICITUD_CERTIFICADOS_ESPECIALES"),
	BANDEJA_ALERTAS("TIPO_DOC_BANDEJA_ALERTA_POR_ENTIDAD"),
	;

	private String is_codigo;
	
	private EnumParametroDocumental(String as_codigo) {
		this.is_codigo = as_codigo;
	}
	
	@Override
	public String getIs_codigo() {
		return is_codigo;
	}

}
