
package co.gov.supernotariado.bachue.clientebus.solicituddecopias.operacion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import co.gov.supernotariado.bachue.clientebus.solicituddecopias.types.consultarsolicitud.ConsultarSolicitudObjectFactory;
import co.gov.supernotariado.bachue.clientebus.solicituddecopias.types.consultarsolicitud.TipoEntradaConsultarSolicitud;
import co.gov.supernotariado.bachue.clientebus.solicituddecopias.types.consultarsolicitud.TipoSalidaConsultarSolicitud;
import co.gov.supernotariado.bachue.clientebus.solicituddecopias.types.ingresosolicitud.IngresoSolicitudObjectFactory;
import co.gov.supernotariado.bachue.clientebus.solicituddecopias.types.ingresosolicitud.TipoEntradaIngresoSolicitud;
import co.gov.supernotariado.bachue.clientebus.solicituddecopias.types.ingresosolicitud.TipoSalidaIngresoSolicitud;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SDI_EE_SolicitudDeCopias", targetNamespace = "https://www.supernotariado.gov.co/services/bachue/ee/solicituddecopias/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    IngresoSolicitudObjectFactory.class,
    ConsultarSolicitudObjectFactory.class
})
public interface SDIEESolicitudDeCopias {


    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.ee.solicituddecopias.ingresosolicitud.v1.TipoSalidaIngresoSolicitud
     */
    @WebMethod(operationName = "IngresoSolicitud", action = "https://www.supernotariado.gov.co/schemas/bachue/ee/solicituddecopias/ingresosolicitud/v1")
    @WebResult(name = "salidaIngresoSolicitud", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ee/solicituddecopias/ingresosolicitud/v1", partName = "salida")
    public TipoSalidaIngresoSolicitud ingresoSolicitud(
        @WebParam(name = "entradaIngresoSolicitud", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ee/solicituddecopias/ingresosolicitud/v1", partName = "entrada")
        TipoEntradaIngresoSolicitud entrada);

    /**
     * 
     * @param entrada
     * @return
     *     returns https.www_supernotariado_gov_co.schemas.bachue.ee.solicituddecopias.consultarsolicitud.v1.TipoSalidaConsultarSolicitud
     */
    @WebMethod(operationName = "ConsultarSolicitud", action = "https://www.supernotariado.gov.co/schemas/bachue/ee/solicituddecopias/consultarsolicitud/v1")
    @WebResult(name = "salidaConsultarSolicitud", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ee/solicituddecopias/consultarsolicitud/v1", partName = "salida")
    public TipoSalidaConsultarSolicitud consultarSolicitud(
        @WebParam(name = "entradaConsultarSolicitud", targetNamespace = "https://www.supernotariado.gov.co/schemas/bachue/ee/solicituddecopias/consultarsolicitud/v1", partName = "entrada")
        TipoEntradaConsultarSolicitud entrada);

}
